src/discussions/comments/reply/Reply.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/messages.js

This PR adds a user's role information e.g "Staff" next to the user's name in the UI.
- [BB-4736](https://tasks.opencraft.com/browse/BB-4736)
- [TNL-7793](https://openedx.atlassian.net/browse/TNL-7793)
- Add some new posts via the LMS discussion forum here http://localhost:18000/courses/course-v1:edX+DemoX+Demo_Course/discussion/forum/ 
- Checkout to this branch `tinumide/add_staff_moderator_markers` in the `frontend-app-discussions` repository
- Start the app and browse the url http://localhost:2002/discussions/course-v1:edX+DemoX+Demo_Course/topics to see the posts

feat: Add staff/moderator markers [BB-4736] [TNL-7793] [BD-38]

---

.eslintrc.js
package-lock.json
package.json
src/components/FormikErrorFeedback.jsx
src/components/TinyMCEEditor.jsx
src/components/index.js
src/data/constants.js
src/discussions/comments/reply/Reply.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/navigation/breadcrumb-menu/messages.js
src/discussions/navigation/navigation-bar/messages.js
src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js
src/discussions/posts/post-actions-bar/messages.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js
src/discussions/posts/post-filter-bar/messages.js
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/messages.js
src/discussions/topics/TopicsView.jsx
src/discussions/topics/topic-search-bar/messages.js
src/discussions/utils.js

This change adds the TinyMCE editor for editing posts and connects the post editor to the API, allowing adding new posts and editing existing ones.
**Creating a new post:**
https://user-images.githubusercontent.com/118837/131846368-b827ac90-c9be-48a4-be85-b9f87a62993e.mp4
**Editing an existing post:**
**Test instructions:**
1. Try creating a new post using the UI
2. After creating the post, you should be redirected to the post after a second or so
3. You can edit and existing post by visiting it, and changing the URL to append /edit 
A future PR will add proper edit buttons etc.

feat: Update the post editor to include TinyMCE and connect to API [BD-38] [TNL-7353]  [BB-2900]

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/CommentEditor.jsx
src/discussions/comments/comment/CommentHeader.jsx
src/discussions/comments/comment/ResponseEditor.jsx
src/discussions/comments/comment/index.js
src/discussions/comments/comment/proptypes.js
src/discussions/comments/data/api.js
src/discussions/comments/data/slices.js
src/discussions/comments/data/thunks.js
src/discussions/comments/messages.js
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/posts/PostsView.jsx
src/discussions/posts/index.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js
src/discussions/posts/post/LikeButton.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/PostLink.jsx
src/discussions/posts/post/index.js
src/discussions/posts/post/messages.js
src/discussions/posts/post/proptypes.js
src/discussions/utils.js

Adds an editor based on tinymce for creating and editing comments and replies. 
Jira: [TNL-8695](https://openedx.atlassian.net/browse/TNL-8695)
https://user-images.githubusercontent.com/118837/133106965-6f8b89b2-fa0e-4bd8-8181-ae187fe43698.mp4

feat: Add editor for replies [BD-38] [TNL-8695]

---

src/discussions/cohorts/data/__factories__/cohorts.factory.js
src/discussions/cohorts/data/__factories__/index.js
src/discussions/cohorts/data/api.js
src/discussions/cohorts/data/index.js
src/discussions/cohorts/data/redux.test.js
src/discussions/cohorts/data/selectors.js
src/discussions/cohorts/data/slices.js
src/discussions/cohorts/data/thunks.js
src/discussions/posts/data/api.js
src/discussions/posts/data/redux.test.js
src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js
src/store.js

Add a field to post editor, which allows to select from course's cohorts.
"All learners" option is always available, and stands for no cohort.
[TNL-8713](https://openedx.atlassian.net/browse/TNL-8713)
As discussions administrator:
- Create a post with a "All learners" cohort (i.e. either don't select anything under "Cohort visibility" field, or select "All Learners" option)
- Create a post with a cohort
- Check that can't edit cohort for an existing post
As normal user:
- Check that "Cohort visibility" field is not visible when trying to create or edit an existing post

feat: add cohort selection [BD-38] [TNL-8713] [BB-4926]

---

src/discussions/posts/post/LikeButton.jsx
src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/messages.js

Adds the cohort name to UI.
**JIRA tickets**: https://openedx.atlassian.net/browse/TNL-8694
**Dependencies**: https://github.com/edx/frontend-app-discussions/pull/28
**Screenshots**: 
**Merge deadline**: "None" 
**Testing instructions**:
1. Enable cohorts and split discussions
2. Post a topic to different cohorts/everyone and see that it shows up correctly. 
**Author notes and concerns**:
The `people` icon is currently not in paragon. 
**Reviewers**

feat: Show cohort info in posts [BD-38] [TNL-8694]

---

src/discussions/topics/data/thunks.js
src/discussions/topics/topic-group/topic/Topic.jsx

The count of questions and discussions was not being passed correctly till the UI from the API response. This fixes the issue making topic counts available in the UI.

fix: topic counts were not included in normalised data [BD-38] [TNL-9403]

---

src/discussions/posts/post-actions-bar/PostActionsBar.jsx

There was an issue with the app where when searching for posts when on the topics page, nothing would happen. Now this will redirect the user to the all posts page from wherever they are when searching and then display the results.

fix: starting a search redirects you to the all posts page [BD-38] [TNL-9336]

---

src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post/Post.jsx

Currently redirecting doesn't preserve query parameters. This change fixes this and fixes all usages of history.push

fix: fixes issues with redirects [BD-38] [TNL-9387]

---

src/data/constants.js
src/discussions/discussions-home/DiscussionsHome.test.jsx
src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/topics/TopicsView.test.jsx

Remove the discussions prefix from the base path to avoid potential repeat of that
word the path when deployed.
Ticket: https://openedx.atlassian.net/browse/TNL-9347

fix: remove discussions from the base path [BD-38] [TNL-9347]

---

src/discussions/comments/data/redux.test.js
src/discussions/comments/data/slices.js

This pull request fixes an issue where selecting different posts in the MFE, would not clear the comments list of the prior posts.
Rather comments of the newly selected posts would get appended to the comments list and would be shown along with the comments of the earlier posts.
1. Select a post with atleast one comment.
2. Select a different post with atleast one comment.
3. Only the comments of the currently selected post should be displayed below the post

fix: selecting different post does not clear comments list [BD-38] [TNL-9423] [BB-5183] 

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/comments/data/__factories__/comments.factory.js
src/discussions/comments/messages.js
src/discussions/common/DeleteConfirmation.jsx
src/discussions/common/index.js
src/discussions/messages.js
src/discussions/posts/data/__factories__/threads.factory.js
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/messages.js
src/discussions/utils.js

Adds delete confirmation dialogs for posts, comments and replies.

feat: delete confirmation dialogs [BD-38] [TNL-9351]

---

src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/discussions-home/DiscussionsHome.test.jsx

- Remove app header and footer for both in-context or non-in-context discussions
While rendering the mfe in an iframe within discussions tab, there is a header and footer rendered as well which seems duplicate as discussion tab already has its own header and footer. 
This PR removes the header and footer so that the rendering within the iframe looks more closer to the mockups. 
FYI: @xitij2000

fix: remove app header and footer

---

src/discussions/posts/post/LikeButton.jsx

As per TNL-9569, made the UI follow the Figma designs more
closely. When there are no likes just show the empty like icon.
- https://tasks.opencraft.com/browse/SE-5348
- https://openedx.atlassian.net/browse/TNL-9569
- Install the package
- Go to the discussions tab for any course
- Click the **View the new experience** button
- Add a post
- Like/unlike the post
The counter should appear when adding a like and disappear if the number of likes == 0.
8 March 2022

[TNL-9569] Like count should not display is zero

---

src/discussions/comments/data/redux.test.js
src/discussions/comments/data/slices.js

Fixes a bug that wouldn't update the UI when making a comment on a response that doesn't have responses.
https://user-images.githubusercontent.com/118837/155137125-8f98968a-c73d-4e80-96d8-e441f28317be.mp4

fix: when making a comment on a response that doesn't have responses [BD-38] [TNL-9563] 

---

src/discussions/posts/post/PostLink.jsx

Ticket: [TNL-9568](https://openedx.atlassian.net/jira/software/c/projects/TNL/boards/713?modal=detail&selectedIssue=TNL-9568)
Non-breaking space Html entity(&nbsp) was showing up in post summery. Now it's rendered properly as a space.

fix: display non-breaking space entity properly in post summary

---

src/discussions/posts/post/PostLink.jsx

Removed the Icon component which is rendering when the post is not read
https://openedx.atlassian.net/browse/TNL-9572

[TNL-9572] Removed legacy indicator for unread post

---

src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/PostFooter.test.jsx
src/discussions/posts/post/messages.js

This PR adds a `X new` badge to the Post link when there are new unread comments.
- https://openedx.atlassian.net/browse/TNL-9573
- https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussion-page?node-id=3975%3A295507
1. Checkout the PR branch
2. Open the test course in the app as a test user at https://localhost:2002/<course_id>
3. Go to LMS Discussion page of the test course as a **different user**
4. Add a couple of comments to existing posts
5. Switch to the discussions frontend app - Go to the topic where the comments were added
6. Notice the `X new` tags in the Post links on the sidebar

[BD-38] [TNL-9573] [BB-5556] Adds an indicator to Post Links for new comments

---

src/discussions/topics/topic-group/topic/Topic.jsx

Count displaying on more than one lines. 
https://openedx.atlassian.net/browse/TNL-9635
Before:
After:

fix: count displaying in multiple lines

---

src/discussions/common/AlertBanner.jsx
src/discussions/common/AlertBanner.test.jsx

Ticket: [TNL-9610](https://openedx.atlassian.net/browse/TNL-9610)
- Font of “Answer” and “Endorsed” string is bigger now.
- Color of username is same as rest of the text.
- Added user role (“Staff”, “TA” etc.) and icon.
- Added more space between timestamp and username.
- Top-right and top-left corner of the header box are rounded.

fix: answered and endorsed indicator modification

---

src/discussions/posts/PostsView.jsx
src/discussions/posts/data/thunks.js

Previously loaded post were disappearing when next posts were loaded.
https://openedx.atlassian.net/browse/TNL-9628
Before:
After:

fix: post summaries disappear upon scroll to the bottom

---

src/data/constants.js
src/discussions/data/selectors.js
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/__factories__/threads.factory.js
src/discussions/posts/data/api.js
src/discussions/posts/data/redux.test.js
src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post-filter-bar/messages.js

Fixes an issue where filtering by post type wasn't working, and simplifies that code a bit.
The code was simply not passing along the post type filter. 
The issue with the `following` filter not working has to do with a bug in the backend, and it is fixed here: https://github.com/openedx/cs_comments_service/pull/375
**Test instructions**
Just test that filtering by discussions and questions works in all posts and my posts.

fix: filtering by post type wasn't working [BD-38] [TNL-9609]

---

src/discussions/posts/post/Post.jsx

Opening the related link in the 'top' frame avoids an issue where the LMS
attempts to load the learning MFE in the discussions tab.

fix: related link for posts should open in top frame [TNL-9647] [BD-38]

---

src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/CommentEditor.jsx
src/discussions/comments/messages.js
src/discussions/posts/post-editor/PostEditor.jsx

If a post or comment has been submitted, clear it from autosaved drafts so that it doesn't show up anymore.
**Test instructions**
- Without checking out this PR do the following:
- Create a new post, and type some text. 
- Cancel the post, and add a new one again, you should see the saved post text.
- Refresh the page, you should see the saved text.
- Submit the post, and try adding a new post, you will still see the saved post. 
- Repeat the above with comments and replies
- After checking out this PR try the above again, and now the text should be retained until the post or comment is saved. Once it's saved the text should no longer be saved.

fix: clear saved post or comment on submit [BD-38] [TNL-9630] 

---

src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostLink.jsx

Fix text leaking out from post summary in case of very long word such , it should fit inside the element.
`verylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongwordverylongword`
Like 
**Test instruction**
- Create a new post with very long word.
- Save it 
- Make sure his summary (or preview) fit inside the post element.

fix : [BB-5597][TNL-9618] [BD-38] text leaking out from post summary

---

src/discussions/data/thunks.js

Send a request to fetch discussion settings only for admins. UI was breaking if a request is sent for other roles.

fix: send request to fetch discussion settings only for admins

---

src/discussions/posts/post/PostLink.jsx

Answered marker is right aligned.

fix: answered marker not right aligned correctly

---

src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/topics/TopicsView.jsx

When a comment is marked as an answer, refresh the post it's in so the answered tag appears.
When navigating to the post tab, refresh the topic list.
https://user-images.githubusercontent.com/118837/160101466-5e47cc4c-80e0-4110-b7e1-15366cca125e.mp4

fix: update post when comment is marked as answer; reload topics on open [BD-38] [TNL-9646] [TNL-9703]

---

src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/empty-posts/EmptyPage.jsx

Makes the empty page illustration be centrally aligned on the page.
Makes the content container expand to take the full vertical space.
**Tickets:**
- https://openedx.atlassian.net/browse/TNL-9627
- https://openedx.atlassian.net/browse/TNL-9684

fix: align empty state in the center and auto-grow container [BD-38] [TNL-9684] [TNL-9627]

---

src/discussions/posts/data/api.js

- TNL TICKET: https://openedx.atlassian.net/browse/TNL-9742
The user was unable to edit the already added post. due to reason code field going in the payload. that has been removed for getting fix.

fix: removed edit reason code

---

src/data/constants.js
src/discussions/comments/comment/CommentHeader.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/posts/post/LikeButton.jsx
src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/PostLink.jsx

Updated UI of post summary and post details:
Font-weight of summary title
Author label color (in both summary and post details)
Border around avatar/profile image (in both summary and post details)
Spacing between avatar and other details
Spacing between the summary footer and content
Enlarge background of like button

fix: UI adjustments to post summary and post details

---

src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/PostLink.jsx

The post summary box is smaller now.

fix: post summary box size is large

---

src/data/constants.js
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/data/api.js
src/discussions/discussions-home/DiscussionContent.jsx
src/discussions/learners/LearnersContentView.jsx
src/discussions/learners/LearnersContentView.test.jsx
src/discussions/learners/data/__factories__/learners.factory.js
src/discussions/learners/data/api.js
src/discussions/learners/data/selectors.js
src/discussions/learners/data/slices.js
src/discussions/learners/data/thunks.js
src/discussions/learners/index.js
src/discussions/learners/learner/CommentsTabContent.jsx
src/discussions/learners/learner/LearnerFooter.jsx
src/discussions/learners/learner/PostsTabContent.jsx
src/discussions/learners/messages.js
src/discussions/posts/data/api.js

This PR implements the content area for the Learners pages. It fetches the threads and comments of the selected user and renders them into 3 tabs
- Posts - `threads` API
- Responses - `comments` API items which are not a child of another comment
- Comments - `comments` API items which are children of other comments
1. Enable learners tab by setting the Course Waffle Flag - `discussions.enable_learners_tab_in_discussions_mfe` for your test course
2. Open the Learners page by clicking on the "Learners" button on the top
3. Now select a specific learner in list to view their contributions
4. Switch between the Posts, Comments and Responses tab to see each kind of posts separately.
1. JIRA Ticket - https://openedx.atlassian.net/browse/TNL-8844
2. Figma Design - …

[BD-38] [TNL-8844] [BB-5014] Learners page to browse posts and comments

---

src/discussions/posts/PostsView.jsx

[TNL-9794](https://openedx.atlassian.net/browse/TNL-9794)
- Switching between subtopics and modules is breaking the UI
- This bug is a ripple effect of [Post not loading change](https://github.com/openedx/frontend-app-discussions/pull/92)
- [Post not loading change](https://github.com/openedx/frontend-app-discussions/pull/92) was breaking the [React Hook Rules](https://reactjs.org/docs/hooks-rules.html) which was the main reason behind this issue. 
- Call a hook inside an if the condition is not allowed So convert the conditional `useSelector` hook call to conditional component calling. 
https://www.loom.com/share/db7ecd88a01a46a4ba07fb1b9f5c0c62

fix: switching between subtopics is breaking the UI

---

package-lock.json

- DIscussions MEF stage build is failing and asking for install the webpack. 
- Package-lock file is re-generated after the node 16 upgrade.

chore: create new package-lock file after node 16 upgrade

---

src/discussions/discussions-home/DiscussionContent.jsx
src/discussions/empty-posts/EmptyPage.jsx

content sections background color changed from light-300 to light-400 to differentiate it from summary cards 
https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussion-page?node-id=2851%3A874102
Figma Mockups Attached.

style: content sections background colour changed

---

src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx

TNL TIcket : [9469](https://openedx.atlassian.net/browse/TNL-9469)
Related Course authoring PR: https://github.com/openedx/frontend-app-course-authoring/pull/284
https://github.com/openedx/edx-platform/pull/30189
This PR is a part of the change mentioned in the above ticket, more related PRs are mentioned
Updated screen after removing allow anonymous post for all.
checkout in all the three mentioned branches in different repos
- configure discussion provider will no longer show toggle-switch to post anonymously
- add post both using new MFE and legacy experience post anonymously options is removed
- for courses already configured to allow post anonymous feature still won't show the option to post anonymously

feat: allow anonymous post support is removed from add post section

---

src/data/constants.js
src/discussions/common/context.js
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/navigation/navigation-bar/NavigationBar.jsx
src/discussions/posts/PostsView.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/post/PostLink.jsx

This fixes two issues. The first is that the topics page can cause constant requests to threads, and the second, that clicking on a post link when browsing a category can cause the application to crash.

fix: Fix constant reloading on topics page and posts links on category page [BD-38] [TNL-9868] [TNL-9846]

---

src/discussions/discussions-home/DiscussionContent.jsx
src/discussions/learners/LearnerPageHeader.jsx
src/discussions/learners/LearnersContentView.jsx
src/discussions/learners/LearnersContentView.test.jsx
src/discussions/learners/LearnersView.jsx
src/discussions/learners/learner/LearnerCard.jsx

- Move the learner header to the home page so it can use full width.
- Remove the menu icon from learner page till there is a menu in place
- Improve styling of header bar and sidebar
|Before|After|
|---|---|
|![Before](https://user-images.githubusercontent.com/118837/164202835-871e8856-48ce-4856-9c1e-5e368aca5bff.png) | ![After](https://user-images.githubusercontent.com/118837/164202825-2d054427-3efb-4668-892b-d35b08b0b8f2.png) |

fix: improve UX to match mockups better [BD-38] [TNL-9841] [TNL-9844]

---

src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/CommentEditor.jsx
src/discussions/comments/comment/ResponseEditor.jsx

- Hide the `Reason for editing` dropdown when the user (with moderator role and not a post/comment author) adds a response or a comment
**Add Response**
**Add Comment**

fix: hide edit reason dropdown while adding a comment or response

---

src/discussions/comments/comment/CommentEditor.jsx
src/discussions/comments/messages.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js

- Add validation for edit reason code dropdown
- Display an error message when the moderator submits a response/comment/post without selecting Edit reason

fix: add validation for edit reason code dropdown

---

src/discussions/posts/PostsView.jsx

Color of pinned bar in post summary was merging with card of posts that was read.
Ticket Link:
https://openedx.atlassian.net/browse/INF-158
Before
After

fix: post summary pinned bar

---

src/data/thunks.js

"Related to" was not displayed on posts related to specific topics on this [course](https://courses.edx.org/courses/course-v1:MITx+7.00x+1T2022).
Reproduced the issue by replicating the API response and fixed it.

fix: "Related to" field not shown on posts

---

src/discussions/comments/comment/Reply.jsx
src/discussions/common/AlertBanner.jsx

- Comment endorse, close, report, edit the reason each alert will display on an individual single row.
- Comment endorse action will remove in the next ticket

fix: display comment actions alert in single row

---

src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/posts/post/Post.jsx
src/index.scss

- High resolution images will be responsive according to screen size in the post, comment, and response content.
**Before**
**After**

fix: make the post, comment, response content images responsive

---

src/discussions/posts/PostsView.test.jsx
src/discussions/posts/post-filter-bar/PostFilterBar.jsx

The reported filter is now available for discussion moderator roles.

fix: reported filter is missing for discussion moderator roles

---

src/discussions/data/thunks.js

Users with discussion moderation roles were not getting the option to create a post for a specific cohort.
Before:
Fixed:

fix: discussion moderators can't create posts for specific cohorts

---

package-lock.json
package.json
src/components/TinyMCEEditor.jsx

- related to the discussion posted in this [document](https://2u-internal.atlassian.net/wiki/spaces/PT/pages/15440774/Tiny+MCE+Plugins). wiris integration with TinyMCE has been reverted. 
for context new plugins will be explored and a decision will be based after keeping in mind all the aspects.

revert: reverting wiris integration

---

src/components/HTMLLoader.jsx
src/components/TinyMCEEditor.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostLink.jsx

TNL Ticket: https://2u-internal.atlassian.net/browse/INF-54
In reference to the ticket above the preview, a package is added for viewing latex in posts but the issue was still occurring in responses and comments and this is resolved in this PR. 
also for experiment with learners experience special characters support plugin is added in TinyMCE

Fix: for rendering latex in comments and responses and support for special symbols in TinyMCE

---

src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js

This PR is part of the effort to improve learners' latex rendering and preview issues. A preview option for the post is added for the TinyMCE content which can be hidden and shown as per user requirement and will provide a preview.
https://2u-internal.atlassian.net/browse/INF-203

feat: added preview option for tinyMCE content

---

src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostLink.jsx

TICKET: https://2u-internal.atlassian.net/browse/INF-231
Image loaded from the legacy experience was not rendering in new MFE due to a change made for rendering MathML in a previous PR. as we no longer using MathML syntax and wiris support has been dropped that change is reverted and MFE will again use `renderedBody` key from API to preview post in different areas, and the ripple effect is reverted. now image uploaded from legacy will be visible in new discussion Experience.

fix: image rendering fix for those uploaded using legacy experience

---

src/discussions/posts/PostsView.test.jsx
src/discussions/posts/post-filter-bar/messages.js

Changed text from "Most votes" to "Most likes" in search filter
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-226
Before
After

fix: change votes to likes in search filter

---

src/components/HTMLLoader.jsx
src/components/PostPreviewPane.jsx
src/discussions/comments/comment/CommentEditor.jsx
src/discussions/posts/post-editor/PostEditor.jsx

- This PR is created to support mathjax visibility while creating/editing posts comments and responses
the details and screenshots with respect to Figma are attached below
FIGMA Screenshots
Application screenshots

feat: added preview option for posts/comments/reponses

---

package-lock.json
package.json

The changes in #34 had to be reverted when an upgrade was made from node 12 to 16 in favor of the test case failure issue. 
This has been re-added and edx config list is updated to the latest version for discussions MFE.

fix: browser support config updated

---

src/components/HTMLLoader.jsx
src/components/PostPreviewPane.jsx

TIcket Link: https://2u-internal.atlassian.net/browse/INF-54, https://2u-internal.atlassian.net/browse/INF-254
This PR covers following two issues:
as preview support was missing for following syntax it has been added in this PR
`[mathjax][/mathjax]`
`[mathjaxinline][/mathjaxinline]`
HTML format was disturbed when adding latex in post. that issue is also resolved, now component will retain the HTML tags

fix: syntax support extended for latex

---

src/components/HTMLLoader.jsx
src/components/PostPreviewPane.jsx
src/discussions/posts/post-editor/PostEditor.jsx

Amir mentioned following issues after testing on stage,
- Regex check was creating an issue in rendering mathjax for custom syntax 
- Show preview button was hiding behind other elements on screen when editing post.
Both these issues are fixed in this PR

Preview options

---

src/index.scss

- Fix the post content images overflow issue. Now images are responsive in the post content area.

fix: post content images overflow

---

src/discussions/posts/data/api.js
src/discussions/posts/data/thunks.js

A list of all posts in a topic is stored in an object for quick lookup. This is used when switching between topics to get the list of posts in that topic. When filters change, the list of posts in a topic is updated and this is picked up by the UI. If changing filters when browsing a topic results in an empty result, this would cause the original list of topics for that topic to be retained, causing the filter to simply not apply. This commit fixes that by resetting the post list in that case.
**Testing instructions**
Before checking out this PR try the following:
- In an empty topic, create a few discussion posts. 
- Navigate to that topic
- Filter that topic by "discussions"
- Now filter by "questions"
- The "questions" filter will not apply. 
- Now try creating one or more question …

fix: filtering posts in a topic doesn't work when filtered results are empty [BD-38] []

---

src/discussions/posts/post-editor/PostEditor.jsx

- Set `All learners` as the default value for cohorts dropdown 
- Cohorts dropdown is only visible in `add new post` for privileged user
- Cohort can not be changed while editing a post for all users

fix: set default value for cohorts dropdown

---

src/discussions/comments/CommentsView.jsx

Thread is not loaded when thread data is not found in the redux store. After this change, it will send an API call to get thread from server.
This issue was found when working on the following ticket
https://2u-internal.atlassian.net/browse/INF-349

fix: load thread if thread data doesnot exist in redux

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/comment-icons/CommentIcons.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/CommentHeader.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/common/ActionsDropdown.jsx
src/discussions/common/AlertBanner.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/common/EndorsedAlertBanner.jsx
src/discussions/common/EndorsedAlertBanner.test.jsx
src/discussions/common/index.js
src/discussions/data/hooks.js
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostHeader.jsx
src/index.scss

1. Spacing between post content area and post summary sidebar
2. Post content area spacing
3. Marked as answer banner alert height
4. Response area spacing
5. Comment area spacing
6. Align and space between comments
7. Multiple alert banners borders are rounded in the comment section
8. Comment and responses text color
9. Endorse Icon color
10. Space between alerts
11. Space between comment/post header and alerts
12. Separate the endorse/ answer alert
13. Load more lint spacing
14. Add a comment button color 
15. Convert time whole alphabet word to a single short character (1 hour ago to 1h)
16. Fix comment and response avatar heigh and weight
17. Align and space between reply
**Figma Mockup**
**Updated UI**

fix: response and comment UI according to Figma

---

src/discussions/common/AuthorLabel.jsx

In case when user is retired show Deactivated instead of user name because user name is converted to hash after it is retired.
Before
After

fix: show deactivated in case of retired user

---

public/index.html
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/discussions-home/DiscussionsHome.jsx

- Fix the scrollbar for the safari browser
- Fix post content bottom extra white space
**White Space issue** 
**Updated UI**

fix: scrollbar for safari

---

src/discussions/comments/CommentsView.jsx
src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js

- That post will be opened and rendered in the All posts tab.
- A Direct link post will display on top of the list then Pinned posts will show, then the remaining posts.
- In the list pane, all remaining posts will load according to the default filters and sorts for the user (learner vs moderator)

fix: display direct link post at top of the list

---

package-lock.json
package.json
src/discussions/discussions-home/DiscussionsHome.jsx
src/index.jsx
src/index.scss

Add back the header and footer components to the MFE, based on `inIframe` query_param.
**NOTE: _theme in screenshot is different to theme that is live on site. Screenshot was just to give an idea of how the header and footer look._**

feat: add header footer for discussion MFE behind inIframe query_param

---

src/components/TinyMCEEditor.jsx
src/data/constants.js

Issue : https://2u-internal.atlassian.net/browse/INF-397
There was no limit for Image upload size on frontend but backed has an upload size limit. ie 1 MB. This PR restricts users from uploading Images larger than 1MB from a frontend text editor. When a user tries to Large image it shows an error like this screenshot.

feat: added image upload size limit

---

src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/CommentHeader.jsx
src/discussions/comments/comment/CommentHeader.test.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/common/AlertBanner.jsx
src/discussions/common/AlertBanner.test.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/common/EndorsedAlertBanner.jsx
src/discussions/common/EndorsedAlertBanner.test.jsx
src/discussions/posts/post/PostHeader.jsx
src/index.scss

- Usernames while viewing a post, response or comment should be clickable.
- Mouseover state of username is underlined + hand icon
**Fixed**

fix: clickable username in post, comments and responses

---

src/discussions/common/time-locale.js

Change timeago detail to show months information in weeks. This is done to differentiate between minutes and month timeago detail (both were previously represented by `m`)

fix: fix timeago detail for months to be in weeks.

---

src/data/constants.js
src/discussions/common/AlertBanner.jsx
src/discussions/common/EndorsedAlertBanner.jsx
src/discussions/data/hooks.js
src/discussions/discussions-home/DiscussionContent.jsx
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/messages.js
src/index.scss

**Description** 
- A back button is added in the post content area for small devices from where users can navigate back to the posts list.
- Back button is working for all tabs post content.
- Posts list items are mobile responsive.
- Sidebar and Post content ratio adjusted according to screen size.
- Set alignment issue for Alert and endorsed banners text on the mobile screen.

feat: add a posts list back button for small devices and improve responsiveness 

---

src/discussions/posts/PostsList.jsx

This PR reloved these issues.
- Pin/unpin posts sorting
- Duplicate posts
- Direct link post will visible in unpin post section

fix: pinned post sorting issue

---

src/discussions/learners/learner/LearnerCard.jsx

Removed learners list footer because we do not want to show learners stats for now because of performance issues.
https://2u-internal.atlassian.net/browse/INF-444
https://github.com/openedx/edx-platform/pull/30847

fix: removed learners list footer

---

src/discussions/comments/comment/Reply.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/posts/post/PostLink.test.jsx

- Move clickable username behind the `discussions.enable_learners_tab_in_discussions_mfe`

Move clickable username behind the discussions.enable_learners_tab_in_discussions_mfe

---

src/discussions/posts/post/PostHeader.jsx

Long Post title was breaking the UI , This PR fixes this issue.
https://2u-internal.atlassian.net/browse/INF-452
1. Create a post with a long title in the discussion forum.
2. Observe UI is not breaking anymore.

Long Post title UI fix

---

src/discussions/common/AuthorLabel.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/learners/learner/LearnerFilterBar.jsx
src/discussions/messages.js
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/PostLink.test.jsx

- changed convention of adding indexTab in string instead of object format --> no related ticket (suggested by jeff)
- anonymous user is not clickable , https://2u-internal.atlassian.net/browse/INF-451

fix: anonymous user is not clickable

---

src/discussions/learners/LearnerPostsView.jsx

No result found text will not be visible in case an API call is in progress.
https://user-images.githubusercontent.com/67791278/185651852-4fedf6e1-e979-48c2-96f7-a301dfa3a58a.mov

fix: no result found text remove when call in progress

---

src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/CommentEditor.jsx
src/discussions/common/AlertBanner.jsx
src/discussions/common/AlertBanner.test.jsx
src/discussions/common/EndorsedAlertBanner.test.jsx
src/discussions/data/__factories__/config.factory.js
src/discussions/data/hooks.js
src/discussions/data/selectors.js
src/discussions/data/slices.js
src/discussions/data/thunks.js
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/learners/learner/LearnerFilterBar.jsx
src/discussions/learners/learner/LearnerFooter.jsx
src/discussions/posts/PostsList.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/PostFooter.test.jsx
src/discussions/posts/post/PostLink.jsx
src/discussions/posts/post/PostLink.test.jsx

- Provide access to features according to user roles as listed in [this document](https://docs.google.com/spreadsheets/d/1g16P_b22xH1oLju4skUVLQZoJd30p35vSx6-wMR2_ME/edit?usp=sharing).
- Users having moderator role land on the All Posts tab with Reported as the selected filter and Most Recent as the selected sort.
- Learners land on the My-Posts tab with Most Recent as the selected sort.

fix: allow actions according to user role and privileges

---

src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/discussions-home/DiscussionsHome.test.jsx

Handle `inIframe` query_param on FE to show header and footer when query_param is `False`.
This happens when a user has a link copied from iFrame view with the query_param set to `False` (edge case).

fix: handle inIframe query_param when it is False

---

src/components/Search.jsx
src/components/SearchInfo.jsx
src/discussions/learners/data/slices.js
src/discussions/messages.js
src/discussions/posts/NoResults.jsx
src/discussions/posts/post-actions-bar/messages.js

Address issues with search functionalities.
Points Addressed:
- Replace `Clear` with `Clear results` for all 4 tabs.
- Match text color of `Showing {count} results for {search string}` for all 4 tabs.
- `Clear results` button should also clear the search string in the search bar in all 4 tabs. As of now, this only happens in Learners tab.
- Navigating to another tab, without clearing the search results, should clear the search results as well as the search bar, in all 4 tabs. As of now, the search string remains there, and nothing happens if i search the same string in the new tab.
- For the learners tab, when the search api is triggered, the list of learners should disappear and a loading icon should appear. This loading icon should disappear once the search is concluded. This behavior …

fix: resolve issues with search functionality

---

src/discussions/posts/post/PostFooter.jsx

Clicking on follow/unfollow button in post summary should not open post
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-371

fix: follow button should not open post

---

src/discussions/learners/LearnersView.jsx
src/discussions/posts/NoResults.jsx
src/discussions/posts/PostsView.jsx
src/discussions/topics/TopicsView.jsx

Vertically centered no results found message.
Also fixed a bug found while working on this task. No Results message was visible when topics tab was opened directly (even if the course has topics).
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-413

fix: vertically centered no results found message

---

src/discussions/posts/data/slices.js

Pinning a thread having “Reported” and “Answered” label removes the “Reported” label, This PR resolves this issue by omitting abuse_flag_count from state update.
https://2u-internal.atlassian.net/browse/INF-432
1. In the new discussion MFE pin a reported post.
2. Observe that the reported tag is still there and visible with the pin icon.

fix: Updated state logic for reported content

---

src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js

On hitting the load more button the already loaded threads in the topics tab were getting lost. This is fixed in this PR

fix: threads lost issue on load more in topics

---

src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/ResponseEditor.jsx
src/discussions/common/ActionsDropdown.jsx
src/discussions/common/ActionsDropdown.test.jsx
src/discussions/data/selectors.js
src/discussions/posts/post-actions-bar/PostActionsBar.jsx
src/discussions/utils.js

In the previous discussion experience, blackout date behavior hid the button to create new posts.
In the new discussion experience, when partners set blackout dates, the learner still sees a button to post, and are still able to fill out the form and submit a post
https://2u-internal.atlassian.net/browse/INF-472
1. Set blackout Dates from course advance settings in CMS.
2. Observe in new MFE `Add a post `, `Add a response`, `Add a comment ` and `edit` buttons are not visible.

feat: added blackout dates implementation

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/comments/data/slices.js
src/discussions/comments/data/thunks.js
src/discussions/posts/post/PostLink.jsx

- Sort order of responses is changing immediately.
- Now responses are displayed in orderBy desc.
- Add position-relative class for summary card question icon

fix: sort order of responses is changing immediately

---

src/data/constants.js
src/discussions/common/ActionsDropdown.test.jsx
src/discussions/messages.js
src/discussions/posts/post/Post.jsx
src/discussions/utils.js

"Copy link" functionality in list of actions for posts. Comment actions should not show "copy link"
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-299
Backend PR:
https://github.com/openedx/edx-platform/pull/30941
For Post
For comment

feat: copy post functionality

---

src/discussions/posts/post-editor/PostEditor.jsx

Made violates-guidelines edit reason code default for admin, it depends on this PR https://github.com/openedx/edx-platform/pull/30984
https://2u-internal.atlassian.net/browse/INF-538
Login with a global staff account and edit other user's posts, observe that in edit reasons `Violates community guidelines` is selected by default.

feat: made violates-guidelines edit reason code default for admin

---

.jest/setEnvVars.js
jest.config.js
src/discussions/discussions-home/InformationBanner.test.jsx
src/discussions/discussions-home/InformationsBanner.jsx

- test cases were false passing as both URLs were picking empty strings from env, this has been fixed
- fixed permission tests according to use cases. 
with that I have just figured out that .env.test. is pretty much useless in our codebase, however, I need to confirm it and look into it for more details, might remove that later as well.

fix: permission fixes added for form

---

src/discussions/learners/data/slices.js
src/discussions/learners/learner/LearnerFooter.jsx

Response+comment count for some learners is showing an extra trailing zero as seen in the screenshot below. This issue is resolved in this PR.
Fixed Learners sorting issue.
https://2u-internal.atlassian.net/browse/INF-553
https://2u-internal.atlassian.net/browse/INF-499

fix: removed extra zero in user stats

---

src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/utils.js

- Fixed Post, My post, and learner post sorting. 
- Recent activity filtering is working
- Removed sorting from the frontend

fix: remove post sorting from frontend

---

src/components/HTMLLoader.jsx

Course teams and learners provided feedback on the mathjax not rendering properly, according to the discovery it. was found the expression starting and ending with double slashes were not supported as in legacy experience, this is now added in mathjax config and MFE now supports that as well along with single slash.

fix: double slash also supported now for mathjax rendering

---

src/discussions/learners/learner/LearnerFooter.jsx
src/discussions/learners/learner/LearnerFooter.test.jsx
src/discussions/learners/messages.js

Updated hover stats. 
- All activity will show the sum of posts, responses and comments. 
- Posts will show number of posts created
- Updated reported icon
After Changes:
Ticket link:
https://2u-internal.atlassian.net/browse/INF-554

fix: added hover to stats

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/ResponseEditor.jsx

UI Refactoring 
- Corrected text for load more comments button
- Moved "Add a response" button below "Load more responses" button
- Change UI of "Load more responses", "Load more comments", "Add a response" and "Add a comment" button according to figma
Before
After

fix: ui refactoring of load more responses and comments button

---

src/discussions/topics/messages.js
src/discussions/topics/topic-group/TopicGroupBase.jsx

- Ticket id:  https://2u-internal.atlassian.net/browse/INF-585
a topic with no name will be rendered as unnamed topic in list without crashing the topics tab or disturbing redering of other topics available in list

fix: unnamed topic crash handled on fe

---

src/data/selectors.js
src/discussions/data/hooks.js
src/discussions/data/hooks.test.jsx
src/discussions/data/selectors.js
src/discussions/data/slices.js
src/discussions/posts/PostsView.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post/PostLink.jsx

For smaller courses, there is a feature under the new provider
for grouping topics at the subsection level so that when
navigating the course, all topics under a subsection show up in
the sidebar instead of just the current unit.
This implements that functionality by checking if the discussion
is loaded in-context, and if grouping at subsection is enabled,
and if so, displaying the current subsection's topics.

feat: Add support for grouping at subsections [BD-38]

---

src/discussions/common/AlertBanner.jsx
src/discussions/data/hooks.js
src/discussions/posts/post/PostLink.jsx

Update **Reported Alert Banner** and **Reported Badge** to use `abuseFlagged` param to show/hide Reported Label on content. 
The `abuseFlagged` param indicates the following for different roles:
- **Moderator Role:** **_Return True if content is reported by anyone._**
- **No Moderator Role:** _**Return True ONLY if content is reported by the user themselves.**_
We can avoid checking for different roles on the current user, and use the already calculated `abuseFlagged` value from backend.

fix: fix for reported alert banner and reported badge

---

src/discussions/data/hooks.js

Related Ticket: https://2u-internal.atlassian.net/browse/INF-612
Learners Tab will be visible to learners.
The above screenshot represents a logged-in user without any moderation privileges who is not admin or TA or has any special roles. The learner tab is visible to the user.

fix: learner tab is now visible irrespective of user role

---

Makefile

The Transifex cli started requiring the `-t` or `--translations` flag in the pull command in order to fetch translations. 
More details on ticket.

fix: add flag for transifex pull command

---

src/discussions/posts/post/PostLink.jsx

Fixed tests that were failing on transifex
Test cases related to reported badge for learners area were fixed. 
Added condition to show reported symbol is post.abuseFlaggedCount. abuseFlaggedCount shows number of responses and replies of post that are marked reported.

fix: fixed failing tests for reported badge in learners post view

---

src/discussions/comments/comment/CommentHeader.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/common/AuthorLabel.test.jsx
src/discussions/posts/post/PostLink.jsx
src/discussions/posts/post/PostLink.test.jsx

- User name is no more clickable in the posts summary list in all 4 tabs
- Add new test cases for an author label component 
https://www.loom.com/share/e191efd27a744ac180d57cb0109de955

fix: convert clickable author label to text in posts summary list

---

package-lock.json
package.json
src/discussions/discussions-home/BlackoutInformationBanner.jsx
src/discussions/discussions-home/BlackoutInformationBanner.test.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/discussions-home/InformationsBanner.jsx
src/discussions/messages.js

Related ticket https://2u-internal.atlassian.net/browse/INF-599
background color change is required which will be based on the Paragon PR merge and version upgrade in this PR - DONE
After paragon upgrade
Note needed paragon upgrade to match Figma designs.

feat: blackout dates information banner added

---

src/components/HTMLLoader.jsx
src/discussions/posts/post-editor/messages.js
src/discussions/topics/data/selectors.js

- this Pr is fixing 3 issues
- console errors are coming due to missing objects in translation files. - fixed
- unnamed topics are crashing FE on visiting the topics tab and while trying to click the add post button.
- lastly, the mathjax syntax support is extended in MFE. by adding 3 new formats in config list

fix: more formats for mathjax support added

---

src/discussions/common/DeleteConfirmation.jsx
src/index.scss

- On Delete  only confirmation pop-up highlights
**Before Fix:**
**After Fix:**
https://user-images.githubusercontent.com/73840786/198048188-58c9443f-be0a-4782-b7fb-76db420c5490.mp4

fix: removed highlighted header-action-bar on confirmation pop-up

---

src/components/FilterBar.jsx
src/data/constants.js
src/discussions/learners/LearnerPostsView.jsx
src/discussions/learners/data/api.js
src/discussions/learners/data/slices.js
src/discussions/learners/data/thunks.js
src/discussions/learners/learner-post-filter-bar/LearnerPostFilterBar.jsx
src/discussions/learners/learner-post-filter-bar/LearnerPostFilterBar.test.jsx
src/discussions/posts/data/slices.js
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post-filter-bar/messages.js

Added filter options in Learners post view
- Thread Type
- All
- Discussions
- Questions
- Status
- Any Status
- Unread
- Reported
- Unanswered
- Unresponded
- Sort
- Recent activity
- Most activity
- Most likes
- Cohorts
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-597

feat: added filter options for learner posts

---

src/components/TinyMCEEditor.jsx
src/discussions/messages.js
src/index.scss

- images with dimensions greater than 999px are not rendering old discussion experience, a heads-up message is added in case the user uploads such an image to suggest updating the image dimensions to avoid inconvenience for users on legacy experience.

feat: added warning for images with large dimensions

---

src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js
src/discussions/topics/messages.js
src/discussions/topics/topic-group/topic/Topic.jsx

INF ticket: https://2u-internal.atlassian.net/browse/INF-629
unnamed categories and subcategories will not be shown as empty place holders and instead will have a string place holders for improving user readability

fix: unnamed category and subcategory strings added

---

src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/thunks.js
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post-filter-bar/messages.js

Addition of not responded posts filter in fetch threads lists API.
**Jira ticket: https://2u-internal.atlassian.net/browse/INF-524
related BE PR: https://github.com/openedx/frontend-app-discussions/pull/286**
**Useful information to include:**
Which edX user roles will this change impact? Common user roles are "Learner".
**Supporting information**
Jira ticket: https://2u-internal.atlassian.net/browse/INF-524
related BE PR: https://github.com/openedx/edx-platform/pull/31275
**Testing instructions**
checkout to this branch and make sure you have the latest changes from cs_comment_service as well
use mehak/INF-475 https://github.com/openedx/frontend-app-discussions/pull/286 of discussions MFE
run devstack and open the filters section in all posts/ and my posts
select not responded from the …

feat: add unresponded posts filter in UI 

---

src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/messages.js

> Topic info moved next to the username, for posts in content-specific discussion topics
> Long topic names are truncated appropriately.
**Before Fix:**
**After Fix:**

Topic information moved next to username

---

src/discussions/common/AuthorLabel.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/messages.js

Reverts openedx/frontend-app-discussions#341
> Topic info moved next to the username, for posts in content-specific discussion topics
> Long topic names are truncated appropriately.
**Before Fix:**
**After Fix:**

Revert "Topic information moved next to username"

---

src/discussions/posts/post/PostFooter.jsx
src/discussions/posts/post/PostLink.jsx

Related Ticket: https://2u-internal.atlassian.net/browse/INF-634
Figma: https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7024%3A307217&t=7aAuK3OFCcZNOo6i-0
Before:
After:

style: design changes for post summary card

---

src/discussions/common/ActionsDropdown.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post/ClosePostReasonModal.jsx
src/index.scss

- Display the action menu dropdown on the left side in the in-context sidebar
- Display the image upload modal in the screen center on the post-creation/edit
- Display close reason modal as mobile size in the in-context sidebar 
- Disable topic select dropdown when use is in-context sidebar. It can only create/edit a post related to the opened topic. 
https://www.loom.com/share/06b3e7c044934fd7aeb09c6112a99819
https://www.loom.com/share/47c4794ef83a45eb86029e6720360f63

fix: incontext modal alignment changes

---

src/discussions/learners/LearnerPostsView.jsx
src/discussions/posts/PostsList.jsx

- count_flagged param sent as true only for Privilege users in learner API
- count_flagged is not required for nonprivileged users in learner API
**Privilege user**
**nonprivileged users**
**Privilege user**
**nonprivileged users**

fix: count_flagged param sent only for Privilege users

---

src/discussions/posts/post/PostHeader.jsx

[INF-578](https://2u-internal.atlassian.net/browse/INF-578)
Long post titles were shifting the menu position downwards. The menu position is fixed and does not move downwards, regardless of post title length.
**Before**
**After**

fix: long post titles does not  shift menu position.

---

src/discussions/posts/post/PostLink.jsx

This works around [a known issue](https://github.com/openedx/paragon/issues/1797) with `Truncate` that in some situations can lead to an infinite loop and subsequent page hang.
1. Set up a devstack on master and fire it up;
2. Clone `frontend-app-discussions` and run it;
3. Create and enable the `discussions.enable_discussions_mfe` waffle flag;
4. Enroll in the Demo course, enter it, and click on Discussions;
5. Create a new post;
After the post is created, the page will hang indefinitely.  Firefox will eventually offer to debug it, and inevitably the code will be stuck inside [this loop](https://github.com/openedx/paragon/blob/8aa2fa66ccfc60857faf580a8dfc8007eaa9efa3/src/Truncate/utils.js#L86-L95). 
This can be reproduced reliably using:
* Ubuntu Linux 22.04.1
* Node 16.17.0
* npm …

fix: Work around `Truncate` infinite loop

---

openedx.yaml

Commit to including the MFE in Open edX releases going forward.

docs: Include in Open edX release

---

src/discussions/comments/CommentsView.jsx
src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/messages.js
src/discussions/posts/data/api.js
src/discussions/posts/data/thunks.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js

[INF-669](https://2u-internal.atlassian.net/browse/INF-669)
Related Backend Change: https://github.com/openedx/edx-platform/pull/31340 
Focus on the IDs of the thread and course in the screenshot to understand the fix:
original course with thread 
course trying to fetch a thread that does not belong to it
also handled for the edit use case

fix: handled thread not found result on frontend

---

src/discussions/data/hooks.js

The breakpoints added for the desktop screen are conflicting and showing mobile view when screen sizes are comparatively smaller than regular desktop screens hence the limit for desktop screens is expanded 
screen views with different resolutions are pasted below:

fix: UI style fixed for medium screens

---

src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/ResponseEditor.jsx
src/discussions/data/hooks.js
src/discussions/data/hooks.test.jsx
src/discussions/data/selectors.js
src/discussions/data/slices.js
src/discussions/posts/post-actions-bar/PostActionsBar.jsx
src/discussions/utils.js

[INF-628](https://2u-internal.atlassian.net/browse/INF-628)
Add a post/response/comment during active blackout dates fixed for all roles in discussions MFE
**Before**
For discussions MFE when blackout dates were active, buttons for adding a post, response, or comment were not visible for some roles.
**After**
For discussions MFE when blackout dates are active, buttons for adding a post, response, or comment are visible for roles as seen below.
- Global staff
- Course staff 
- Course admin
- Disc. admin
- Disc. moderator
- Disc. TA 
- Disc. Group TA

fix: add a post/response/comment during active blackout dates fixed for all roles

---

src/discussions/learners/data/slices.js

Add event for learner sorting in discussions MFE. The event will be triggered every time a sort is applied on learners tab.
Event name will be `edx.forum.sort.user`

feat: add event tracking for user sorting on learners tab in discussions MFE.

---

src/components/NavigationBar/data/api.js
src/data/api.js
src/data/constants.js
src/data/redux.test.js
src/discussions/cohorts/data/api.js
src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/data/api.js
src/discussions/comments/data/redux.test.js
src/discussions/common/AuthorLabel.test.jsx
src/discussions/data/api.js
src/discussions/data/hooks.test.jsx
src/discussions/discussions-home/DiscussionSidebar.test.jsx
src/discussions/empty-posts/EmptyPosts.test.jsx
src/discussions/empty-posts/EmptyTopics.test.jsx
src/discussions/learners/LearnerPostsView.test.jsx
src/discussions/learners/LearnersView.test.jsx
src/discussions/learners/data/api.js
src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.test.jsx
src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/api.js
src/discussions/posts/data/api.test.js
src/discussions/posts/data/redux.test.js
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post/PostLink.test.jsx
src/discussions/topics/TopicsView.test.jsx
src/discussions/topics/data/api.js

frontend-platform supports runtime configuration since 2.5.0 (see [the PR](https://github.com/openedx/frontend-platform/pull/335) that introduced it), but it requires MFE cooperation.  This implements just that: by avoiding making configuration values constant, it should now be possible to change them after initialization.
Almost all changes here relate to the `LMS_BASE_URL` setting, which in most places was treated as a constant.
This should be a NOOP for any deployments of the MFE that _don't_ make explicit use of runtime configuration.  This is reflected in all unit tests, which needed little to no significant modifications.  This change should have no effect on usage of this MFE in the devstack or in current production deployments.
To actually see the desired effects of the change, …

feat: Support runtime configuration

---

src/discussions/posts/data/slices.js

Add event for content filtering and sorting in discussions MFE. The event will be triggered every time a sort / filter is applied on content.
Event name will be `edx.forum.filter.content`

feat: add tracking event for content filtering in discussion MFE

---

src/discussions/posts/PostsList.jsx
src/discussions/posts/PostsView.jsx
src/discussions/posts/data/slices.js
src/discussions/posts/data/thunks.js

[https://2u-internal.atlassian.net/browse/INF-692](url)
Filters now working fine on all tabs:
Also tested for load more functionality

fix: filter result rendering fixed in topics

---

src/components/NavigationBar/data/api.js
src/data/api.js
src/data/constants.js
src/data/redux.test.js
src/discussions/cohorts/data/api.js
src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/data/api.js
src/discussions/comments/data/redux.test.js
src/discussions/common/AuthorLabel.test.jsx
src/discussions/data/api.js
src/discussions/data/hooks.test.jsx
src/discussions/discussions-home/DiscussionSidebar.test.jsx
src/discussions/empty-posts/EmptyPosts.test.jsx
src/discussions/empty-posts/EmptyTopics.test.jsx
src/discussions/learners/LearnerPostsView.test.jsx
src/discussions/learners/LearnersView.test.jsx
src/discussions/learners/data/api.js
src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.test.jsx
src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/api.js
src/discussions/posts/data/api.test.js
src/discussions/posts/data/redux.test.js
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post/PostLink.test.jsx
src/discussions/topics/TopicsView.test.jsx
src/discussions/topics/data/api.js

Reverts openedx/frontend-app-discussions#377
The discussions MFE is broken on stage. My assumption is that this PR is the culprit

Revert "feat: Support runtime configuration"

---

src/discussions/learners/data/slices.js
src/discussions/learners/learner-post-filter-bar/LearnerPostFilterBar.jsx
src/discussions/learners/learner/LearnerFilterBar.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/slices.js
src/discussions/posts/post-filter-bar/PostFilterBar.jsx

This PR cleans up code for events.
The events were being triggered when the MFE loaded, because the event triggers were in the `slice.js` files. This PR addresses this issue by moving the event logic in `handleChange` function instead, that will be triggered only when the filters change.
The PR also includes coverage for the `contentFilter` event on the learners tab filters.

fix: cleanup events and add filter content event to learners tab filters

---

src/discussions/posts/post-filter-bar/PostFilterBar.jsx

Fix cohortFilter field in content filter event.
We were sending all cohorts present for course. This PR fixes this issue, by replacing it with the current selected cohort.

fix: fix cohort field on content filter event.

---

src/discussions/comments/CommentsView.jsx

[INF-684](https://2u-internal.atlassian.net/browse/INF-684)
If there are no responses that have been marked as answer, the “No endorsed responses” section should not appear. Like in the case of Discussion type post.
**Before:**
**After:**
[7b5a56f0-fbbc-4e39-9fb6-1fe473617a9e.webm](https://user-images.githubusercontent.com/73840786/208659428-1e0a4c04-88c9-448e-9cb3-371e5b2264f5.webm)

fix: removed no endorsed responses from question type post

---

src/components/NavigationBar/data/api.js
src/data/api.js
src/data/constants.js
src/data/redux.test.js
src/discussions/cohorts/data/api.js
src/discussions/comments/CommentsView.test.jsx
src/discussions/comments/data/api.js
src/discussions/comments/data/redux.test.js
src/discussions/common/AuthorLabel.test.jsx
src/discussions/data/api.js
src/discussions/data/hooks.test.jsx
src/discussions/discussions-home/DiscussionSidebar.test.jsx
src/discussions/empty-posts/EmptyPosts.test.jsx
src/discussions/empty-posts/EmptyTopics.test.jsx
src/discussions/learners/LearnerPostsView.test.jsx
src/discussions/learners/LearnersView.test.jsx
src/discussions/learners/data/api.js
src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.test.jsx
src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx
src/discussions/posts/PostsView.test.jsx
src/discussions/posts/data/api.js
src/discussions/posts/data/api.test.js
src/discussions/posts/data/redux.test.js
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post/PostLink.test.jsx
src/discussions/topics/TopicsView.test.jsx
src/discussions/topics/data/api.js

(This reintroduces the change in 9f84230c that was later reverted by 67b0b33a.)
frontend-platform supports runtime configuration since 2.5.0 (see the PR that introduced it[1], but it requires MFE cooperation.  This implements just that: by avoiding making configuration values constant, it should now be possible to change them after initialization.
Almost all changes here relate to the `LMS_BASE_URL` setting, which in most places was treated as a constant.
[1] https://github.com/openedx/frontend-platform/pull/335

feat: Support runtime configuration (second attempt)

---

src/index.scss

After Fix:
The toolbar is not going over the sticky top also the user menu drop-down stays above the sticky header now.
https://user-images.githubusercontent.com/67791278/209301165-1bce0518-aabb-43ee-9966-1d1b65831694.mov

style: z-index fixes for UI elements in user dropdown and editor toolbar

---

src/components/TinyMCEEditor.jsx

[INF-679](https://2u-internal.atlassian.net/browse/INF-679)
The TinyMCE was converting the same domain URLs to relative links hence when copied from My post it changed the URL to  `post/postId` only and when copied from the All Posts tab to `postId` only and then when redirecting it was picking current URL and appending the relative URL to current hence the faulty URL issue. 
for more context on the related setting change consult this documentation
https://www.tiny.cloud/docs/tinymce/6/url-handling/

fix: disabled relative link

---

src/discussions/posts/post-editor/PostEditor.jsx

- edit reason was sent in API in any case if the logged-in user is global staff, now it will only be sent when the requirement to send reason code is met. 
edited global staff post

fix: post edit reason will not be sent in case of global staff own post

---

src/discussions/posts/data/slices.js

[INF-683](https://2u-internal.atlassian.net/browse/INF-683)
Loading icon and filter menu shows when api call is in progress in My posts tab.
Before
After

fix: loading icon and filter menu shows when api call is in progress

---

src/discussions/comments/comment/Reply.jsx
src/discussions/posts/PostsList.jsx

[INF-403](https://2u-internal.atlassian.net/browse/INF-403)
- Moved Spinner to Center in Post summary List
- Reply menu Icon button is moved to top right corner of reply box
**Before**
**After**

fix: moved spinner to center and reply menu icon to right side

---

src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/posts/post/PostLink.jsx
src/discussions/posts/post/PostSummaryFooter.jsx
src/discussions/posts/post/messages.js
src/index.scss

INF-681
UX did some discoveries and created a new layout to increase content density, because of lots of feedback about it.
Mockups can be found here: [Discussions](https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7332%3A316353&t=QhWkFQjlb50HPqvb-0) 
Following are the updates mentioned in the video and Figma:
- Replace icon buttons with icons for like, comment, and follow signs. these will not be action buttons anymore.
- change icon colors/ time stamps to grey-700 
- add elevation (box-shadow-centered-1) for the sidebar
- shrink icon sizes according to Figma
- change line height to 24px for post titles and usernames
- change font sizes according to Figma
- manage card dimensions according to Figma
FIGMA
PLATFORM

style: post summary card design updates

---

src/discussions/in-context-topics/TopicPostsView.jsx
src/discussions/in-context-topics/TopicsView.jsx
src/discussions/in-context-topics/data/selectors.js
src/discussions/in-context-topics/data/slices.js
src/discussions/in-context-topics/data/thunks.js
src/discussions/in-context-topics/messages.js
src/discussions/in-context-topics/topic/ArchivedBaseGroup.jsx
src/discussions/in-context-topics/topic/index.js
src/discussions/posts/data/slices.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/messages.js

- Added archived topics in the post editor for non-learner users and archived topics would only be visible only if in-context is enabled.
- Display archived topics in the topics list
- Display the subsection name as the title when there are no units available in that subsection 
- Clear the posts filters and sort which is affecting the topic posts

feat: display archived topics is post editor and topics list

---

src/discussions/in-context-topics/TopicsView.jsx

1. InContext topics API call in progress status is creating a UI glitch. 
2. Topics are getting screen center every loading 
https://www.loom.com/share/07b70e07e32d47ca9c3b2ff788f82037

fix: inContext topics screen center issue on every loading

---

src/discussions/messages.js

https://2u-internal.atlassian.net/browse/INF-707
Change the blackout info banner to say: `“Posting in discussions is temporarily disabled by the course team”.`
instead of `Blackout dates are currently active. Posting in discussions is unavailable at this time.`

fix: text update for blackout dates banner

---

src/discussions/posts/data/slices.js
src/discussions/posts/post/Post.jsx

1. Deleting a post from the sidebar renders the entire MFE in the sidebar because of redirection after the delete a post.
2. `inContextSidebar` search param is compulsory to render the inContext sidebar UI which was missing in the redirection URL.
**Bug Demo**
https://user-images.githubusercontent.com/79941147/211270814-d6ed8567-cc70-4eac-8030-3c6f261a0ba0.mov
**Fix Demo**
https://www.loom.com/share/5cec274508d345a095844d2563f899a2

fix: deleting a post from sidebar renders entire MFE in the sidebar

---

src/discussions/posts/post/Post.jsx

The delete post function was creating delay to update the UI because redirection is happing before the redux state update. So change the function to async and wait to update the redux state. After the state update, redirect to the required page.
**Bug Demo**
https://www.loom.com/share/e4ac107578e64bfa9e02d4ddcdfe3d22

fix: update post delete function to async

---

src/components/PostPreviewPane.jsx
src/discussions/posts/post-editor/PostEditor.jsx

https://2u-internal.atlassian.net/browse/INF-720
Description: post add and edit section of discussion is redesigned according to the new styles in Figma 
- remove the divider between fields
- fix the spacing between fields according to Figma
- change heading font size to 14px and line height to 16px
- change radio buttons font size to 14 
- fix margins and paddings between different component
Figma: https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7293%3A305649&t=kz1f1XRad1WooYLW-0
Before :
After:

style: fixes add/edit post section redesigned

---

src/discussions/common/AlertBanner.jsx

Now global staff is privileged to these actions.
1. Can see “closed by” info banner on other’s posts - Yes
2. Can see “closed by” info banner on own posts - Yes
3. Can see “edited by” info banner on other’s content - Yes
4. Can see “edited by” info banner on own content - Yes
**Note: edx is a global staff**

fix: editedBy and closedBy banner will be visible to global staff

---

.github/workflows/ci.yml
package-lock.json
package.json

Ticket
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)
Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov 
uninstalled deprecated es-check package

Moving code coverage from codecov package to CI 

---

src/index.scss

[INF-759](https://2u-internal.atlassian.net/browse/INF-759)
Text was overflowing on this for mathjax content.
**Before**
**After**

fix: fix mathjax text overflowing

---

src/components/PostPreviewPane.jsx
src/discussions/comments/CommentsView.jsx
src/discussions/comments/comment/Comment.jsx
src/discussions/comments/comment/Reply.jsx
src/discussions/common/AlertBanner.jsx
src/discussions/common/AuthorLabel.jsx
src/discussions/common/HoverCard.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/learners/LearnerPostsView.jsx
src/discussions/learners/learner/LearnerCard.jsx
src/discussions/posts/post-actions-bar/PostActionsBar.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/posts/post/LikeButton.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostHeader.jsx
src/discussions/posts/post/PostLink.jsx
src/discussions/posts/post/PostSummaryFooter.jsx
src/index.scss

[INF-740](https://2u-internal.atlassian.net/browse/INF-740)
UX did some discoveries and created a new layout to increase content density, because of lots of feedback about it.
Mockups can be found here: [Discussions](https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7332%3A316353&t=QhWkFQjlb50HPqvb-0)
Following are the updates mentioned  and Figma:
- change size of postactionbar in in-context discussions
- change postfilterbar text color and icon size
- change side bar icon sizes according to figma
- change margin for post according to Sigma
- change add a post style according to figma

style:  in-context discussions style updates

---

src/components/TinyMCEEditor.jsx

Tiny MCE was appending the base URL to the URLs added using anchor tags:
https://2u-internal.atlassian.net/browse/INF-765
- Make a new post.
- Switch to the HTML editor.
- Type in <a href="[www.example.com](https://www.google.com/url?q=http://www.example.com&sa=D&source=docs&ust=1675836215078258&usg=AOvVaw0ld9Hw3RaVrWyrMIMlSWfJ)">[www.example.com](https://www.google.com/url?q=http://www.example.com&sa=D&source=docs&ust=1675836215078317&usg=AOvVaw1jeGPgeio8e_20XyjmuGUI)</a>
- Click "save" to go back to the rich text editor.
- Click "HTML" again. Your code now says <a href="/course-v1:HarvardX+PH527x+1T2021/category/[www.example.com](https://www.google.com/url?q=http://www.example.com&sa=D&source=docs&ust=1675836215078375&usg=AOvVaw3-KPYlKUWc_MEs4ujpew-P)">[www.example.com](https://www.googl …

fix: restrict tiny mce from converting url

---

src/discussions/posts/post/Post.jsx

[INF-760](https://github.com/openedx/frontend-app-discussions/pull/new/inf-760)
- Topic name was not visible on posts in in-context discussions block. 
- Topic's visibility was bound to topics but we don't have topics when in-context discussions are enabled, we have only topic context.
- I changed the dependency of topic visibility to topic context only.
1. Go to the learning MFE tab for a course with enabled in-context discussion.
2. Select discussions tab.
3. Select any post on any unit.
4. You will see the topic at the end of the post content.
**Before**
**After**

fix:topic info is fixed from posts in in-context discussions

---

src/components/HTMLLoader.jsx
src/discussions/data/hooks.js

https://2u-internal.atlassian.net/browse/INF-702
The preview updates quickly and when Mathjax is involved and the screen updates too frequently, it is recomended to add a delay before updating previews.
Please describe in detail how you tested your changes. 
Uploading Screen Recording 2023-02-14 at 4.49.11 PM.mov…

feat: added delay in post preview to avoid flashing of content

---

src/discussions/posts/post/Post.jsx

Copy Link was not working on discussion sidebar in frontend-app-learning. CourseId was null when post link was copied from discussion sidebar
Open discussion sidebar in a unit in frontend-app-learning. Select a post and click on "Copy Link" button in post actions.

fix: copy link not working in in-context discussion

---

src/discussions/posts/PostsView.jsx
src/discussions/posts/PostsView.test.jsx

[INF-761](https://2u-internal.atlassian.net/browse/INF-761)
selecting filter and sort had no effect in a discussion sidebar.
Changed selector to selectAllThreads in case of discussion sidebar instead of the selectTopicThreads that wasn't fetching filtered posts correctly.
**Before**
https://user-images.githubusercontent.com/73840786/219065963-297bdb1f-028f-4ef3-bbeb-b8be18f80703.mov
**After**

fix: fix filter and sorting effect in discussion sidebar

---

src/components/TopicStats.jsx
src/components/index.js
src/discussions/in-context-topics/topic/SectionBaseGroup.jsx
src/discussions/in-context-topics/topic/Topic.jsx

Added stats at sub-section level in topics tab.
Ticket: [INF-763](https://2u-internal.atlassian.net/browse/INF-763)
Open Topics tab in discussions mfe. Stats will be visible for courseware topics
Before
After

feat: added stats at subsection level in topics tab

---

src/discussions/post-comments/PostCommentsView.jsx
src/discussions/post-comments/PostCommentsView.test.jsx

**[INF-783](https://2u-internal.atlassian.net/browse/INF-783)**
To create the comment sort feature noticeable by users, our team is working on a product tour. This PR is temporarily hiding the comment sort feature. This feature will be enabled after the product tour implementation.
1. Go to Discussion MEF 
2. Select the Post tab
3. Select a post that has at least one comment
4. Comment sort dropdown will be visible
**Before**
**After**
* [❌ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [✅ ] Is there adequate test coverage for your changes?
* [ ❌] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [😊 ] 🎉 🙌 Celebrate! Thanks for your contribution.

feat: hide the comments sort feature

---

src/discussions/in-context-topics/topic/SectionBaseGroup.jsx

Sub-sections will have same visual as of course-wide topics. Removed additional padding
Open discussions MFE and click on Topics Tab. Subsections will be visible
Before
After

fix: reduced padding for topic names

---

src/discussions/in-context-topics/TopicsView.test.jsx
src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
src/discussions/in-context-topics/data/redux.test.js
src/discussions/in-context-topics/data/selector.test.jsx

INF-723
https://2u-internal.atlassian.net/browse/INF-723
This PR includes 9 test cases for v3 Topics and units list page.
1.  Course-wide/nonCourseware topics will be listed on top, along with their stats.
a. A nonCourseware topic should be clickable and should have a title.
b. A nonCourseware topic should be on the top of the list. Check it using a divider should be only on the bottom.
c. A nonCourseware topic should have 3 stats and should be hoverable.
2. Afterward, sections and subsections will be listed. No stats will be shown here.
a. Section groups should be listed in the middle of the topics list. Check it using the divider should be at the top and 
bottom.
b. A section group should have only a title and required subsections. e.g 2 subsections and should not have the stats.
c. The …

test: added  test cases for v3 Topics and units list page

---

src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx

After creating a new post when user clicks on add a post button form was keeping data from previous added post , This PR resolves this issue.
1. Create a post in in-context mode.
2. Click on Add a post button again.
3. Observe the post title and content fields are empty

fix: resolved data retention issue in add a post form

---

src/discussions/data/hooks.js
src/discussions/discussions-home/DiscussionsHome.jsx

Incontext discussion was crashing because blocks data was not available
Open discussion side bar in any unit. Now it will show threads

fix: incontext crashing

---

src/discussions/in-context-topics/TopicPostsView.test.jsx
src/discussions/in-context-topics/data/api.js
src/discussions/in-context-topics/topic-search/TopicSearchBar.jsx

INF-724
Link: https://2u-internal.atlassian.net/browse/INF-724
Added test cases for the unit posts list, non-courseware topic posts, and filtered topics list
1. NonCourseware topic should display a list of posts when clicked on it.
a. It should have a required number of post lengths. 
b. It should have a Back navigation bar with selected nonCourseware and a topic title.
2. Clicking on a unit will display a list of posts of the selected unit.
a. It should have a required number of post lengths. 
b. It should have a Back navigation bar with a selected unit title.
3. A “back” button will be available to go back to (This point is related to the courseware topic)
a. From the list of posts to the parent/selected unit
i. It should have a list of units and the previously selected unit should be …

test: Added test cases for noncourseware and courseware topic posts

---

src/discussions/post-comments/comments/comment/Comment.jsx
src/discussions/posts/post/Post.jsx
src/index.scss

[INF-799](https://2u-internal.atlassian.net/browse/INF-799)
The actions menu that appears on hover on post/comment, is not accessible via the keyboard which is fixed.
**Before**
**After**
[4ae641d6-be51-4aef-b7dd-137b275dabba.webm](https://user-images.githubusercontent.com/73840786/221651683-612cef08-e450-4094-b19a-31d7bf8286c2.webm)

fix: fixed post coment actions menu accessibilty for keyboard

---

src/discussions/common/ActionsDropdown.jsx
src/discussions/post-comments/comments/comment/Comment.jsx
src/discussions/post-comments/comments/comment/Reply.jsx
src/discussions/posts/post/Post.jsx

More actions was not visible in in-context discussion and was not in place in discussions tab
Open a post in discussions tab or in in-context iframe. Click on more-action button (...) on post. Dropdown will appear
Discussion Tab Post
Discussion Tab Response

fix: more actions dropdown was not visible

---

src/discussions/learners/LearnersView.test.jsx
src/discussions/learners/data/__factories__/learners.factory.js
src/discussions/learners/data/api.js
src/discussions/learners/data/api.test.jsx
src/discussions/learners/data/redux.test.jsx
src/discussions/learners/data/selector.test.jsx
src/discussions/learners/test-utils.js
src/test-utils.js

**[INF-793](https://2u-internal.atlassian.net/browse/INF-793)**
Add test cases for redux store manipulation, API responses, selector, and important Util functions.
1. API responses
a. Successfully get API response for the learner's list(learners profile) and learners posts(threads)
b. Successfully store learners and learnerPosts API data in redux
c. Failed to fetch learners
d. Failed to fetch learner posts
e. denied to fetch learners
f. denied to fetch learner posts
2. Learners redux store 
a. Successfully load initial states in redux
b. Successfully store a learner posts stats data as pages object in redux
c. Successfully store the nextPage, totalPages, totalLearners, and sortedBy data in redux
d. Successfully update the learner's sort data in redux when selecting a different sort other …

test: added testcases of redux, selector and api

---

src/discussions/common/HoverCard.test.jsx
src/discussions/post-comments/PostCommentsView.test.jsx
src/discussions/post-comments/comments/comment/CommentEditor.jsx
src/discussions/post-comments/data/api.js
src/discussions/post-comments/data/hooks.js
src/discussions/post-comments/data/thunks.js
src/discussions/posts/data/api.js
src/discussions/posts/data/thunks.js
src/discussions/posts/post-editor/PostEditor.jsx

send `enableInContextSidebar` param to backend to identify source of content for events. We are doing this to provide flexibility in terms of events analysis (to determine generation of content through new in-context sidebar)
Targeted events are as follow:
- `edx.forum.thread.created`
- `edx.forum.response.created`
- `edx.forum.comment.created`
- `edx.forum.thread.viewed`
Related PR on platform -- https://github.com/openedx/edx-platform/pull/31849

feat: send enableInContextSidebar param to backend to identify source of content for events

---

src/discussions/common/HoverCard.test.jsx
src/discussions/data/hooks.js
src/discussions/post-comments/PostCommentsView.jsx
src/discussions/post-comments/PostCommentsView.test.jsx
src/discussions/post-comments/comments/CommentsSort.jsx
src/discussions/post-comments/data/slices.js
src/discussions/tours/constants.js
src/discussions/tours/data/redux.test.js
src/discussions/tours/data/selectors.js
src/discussions/tours/data/slices.js
src/discussions/tours/data/thunks.js
src/discussions/tours/data/tours.factory.js
src/discussions/tours/messages.js

This PR adds a new product tour for the response sort feature. Responses will be sort as Newest first by default
[INF-782](https://2u-internal.atlassian.net/browse/INF-782)
[INF-781](https://2u-internal.atlassian.net/browse/INF-781)
1. Tested with both tours enabled.
2. Tested with one tour enabled i.e response_sort.
3. Tested with response_sort tour not available in API
4. Tested with Newest first responses sort
https://user-images.githubusercontent.com/26253150/222651490-e5a17a73-7cbb-4733-b544-a357ac524b75.mov

feat: added product tour for response sort

---

src/index.scss

The problem with "quote" block was found on the MFE Discussion. When we are writing a post - we can immediately see normal view for quote, with padding and left border. But in preview window - quote block appears without border, margin and padding, like a regular text. The same situation with published post
We made minor changes in css and checked the result in preview mode and published post
and published post

fix: Fix for code block formatting on the post preview and published post view

---

src/components/Search.jsx
src/discussions/data/api.js
src/discussions/learners/LearnersView.test.jsx
src/discussions/learners/data/__factories__/learners.factory.js
src/discussions/learners/learner/LearnerFilterBar.jsx

[INF-303](https://2u-internal.atlassian.net/browse/INF-303)
1. learner's filter bar
a. It should display the learner’s filter bar.
i. most activity should be selected by default for the non-moderator role and Recent activity should be selected by 
default for moderator roles.
b. It should display learners by most activity when selecting the most activity filter.
c. It should display learners by Recent activity when selecting the Recent activity filter.
2. learners list
a. It should display a learner's list.
b. It should display an avatar, a learner name, and activity stats for each learner tile and it should be clickable. 
3. learners search
a. If the search result is not found, It should have a search query bar with a clear results button and no results found 
text.
b. If the search …

test: added test cases for learner view

---

src/discussions/learners/LearnerPostsView.test.jsx
src/discussions/learners/test-utils.js

[INF-792](https://2u-internal.atlassian.net/browse/INF-792)
Added test case for the following area
1. learner title bar
a. It should display a title bar, a learner name, and a back button
b. It should redirect to the learners list when clicking on the back button
2. learners posts filter
a. It should display a post-filter bar and All posts sorted by recent activity text as default.
3. learner posts list
a. It should display a list of the interactive posts of a selected learner and the posts count should be equal to the API 
response count. 
npm run test
* [✅] Is there adequate test coverage for your changes?

test: added test cases for learner post view

---

src/components/HTMLLoader.jsx
src/discussions/post-comments/PostCommentsView.test.jsx

[INF-812](https://2u-internal.atlassian.net/browse/INF-812)
Currently, Discussions MFE has many frequent JS errors on the new relic dashboard. 
This PR resolves Typeset failed: Cannot set properties of null (setting 'innerHTML') undefined"
- This error was due to the setting of the innerHTML of a null or undefined element. 
- This was happening because useRef was trying to set the element to **sanitizedMath** even before that element appears on the web page.
- So it was resolved by checking if previewRef is not null

fix: fix typeset failed error

---

src/components/HTMLLoader.jsx

[INF-812](https://2u-internal.atlassian.net/browse/INF-812)
Description
Currently, Discussions MFE has many frequent JS errors on the new relic dashboard.
This PR intends to resolve `typeset failed:e.typesetPromise is not a function`
This PR is to for testing purpose, if this fix resolves error or not, also it does not effect MFE in any other way.

temp: fix for typeset failed:e.typesetPromise is not a function

---

src/discussions/posts/post/Post.jsx

When MFE uses path-based deployment (common domain for all MFEs divided by path) - the copied link leads to 404 error.
The fix:
- construct a Post URL using MFE's `PUBLIC_PATH` env var
- works for both subdomain and subdirectory-based deployments
Note:
LMS recently started to use the discussions sidebar which has the same button "Copy Link", but it uses its own env variable `DISCUSSIONS_MFE_BASE_URL`

fix: post sharing URL

---

src/discussions/utils.js

[INF-529](https://2u-internal.atlassian.net/browse/INF-529)
Lock icon is  used for post close and LockOpen icon is used for reopen action in actions menu.
**Before**
**After**

fix: lock is used for post close or reopen

---

src/discussions/post-comments/comments/comment/Comment.jsx

[INF-381](https://github.com/openedx/frontend-app-discussions/pull/new/Ayesha/inf-381)
Remove outline around posts and response/comment cards
**Before**
**After**

fix: removes outline around comment cards

---

src/components/TopicStats.jsx
src/discussions/topics/topic-group/topic/Topic.jsx

[INNF-624](https://2u-internal.atlassian.net/browse/INF-624)
In topic stats, tooltips are aligned to the side, instead of the top.

style: tooltips aligned to the side in topic stats

---

src/components/HTMLLoader.jsx

[INF-840](https://2u-internal.atlassian.net/browse/INF-840)
Description
Currently, Discussions MFE has many frequent JS errors on the new relic dashboard.
This PR intends to `resolve  typeset failed: window.MathJax.typesetClear is not a function`

fix: typeset failed: window.MathJax.typesetClear is not a function

---

src/discussions/learners/data/selectors.js
src/discussions/learners/learner/LearnerAvatar.jsx
src/discussions/post-comments/comments/comment/CommentHeader.jsx
src/discussions/post-comments/comments/comment/Reply.jsx
src/discussions/posts/data/selectors.js
src/discussions/posts/post/PostHeader.jsx

[INF-385](https://2u-internal.atlassian.net/browse/INF-385)
Fixed dynamic image issue by displaying dummy avatar to make it consistent throughout the discussion MFE.
How Has This Been Tested?
Please describe in detail how you tested your changes.
**Before**
**After**

fix: fixed dynamic learner profile issue

---

src/index.scss

[INF-817](https://2u-internal.atlassian.net/browse/INF-817)
We need to move the feedback button towards the bottom right in the Discussion tab and in the sidebar to avoid overlap with post content and summary, respectively.
As of now, it overlaps with post summary/content.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
| <img width="622" alt="Screenshot 2023-04-17 at 11 50 50 AM" src="https://user-images.githubusercontent.com/72802712/232407482-da6baa2f-0c3e-4a1c-bb38-de1b2ff40e1a.png">|<img width="626" alt="Screenshot 2023-04-17 at 11 50 13 AM" src="https://user-images.githubusercontent.com/72802712/232407525-e38d6d7c-494f-4006-a7ad-ad2b1f6fe7e7.png">|

fix: fixed feedback widget position issue

---

src/discussions/common/AlertBanner.jsx
src/discussions/common/AlertBar.jsx
src/discussions/common/AuthorLabel.jsx

[INF-818](https://2u-internal.atlassian.net/browse/INF-818)
1. Role info needs to be present in edited and closed banner.
2. Username and role color in the banner should match figma.
|Before|After|
|   <img width="562" alt="Screenshot 2023-04-14 at 3 54 29 PM" src="https://user-images.githubusercontent.com/72802712/232026106-d56575d1-5eb4-4c0e-8ac5-ab51ea13b7cf.png">   |   <img width="532" alt="Screenshot 2023-04-18 at 2 40 47 PM" src="https://user-images.githubusercontent.com/72802712/232737967-a856502c-2fe1-4a72-9573-752447e46cf1.png">  |

fix: added role for editedby and closedby user

---

src/index.scss

[INF-848](https://2u-internal.atlassian.net/browse/INF-848)
Response sort modal popup is displayed above the actions dropdown menu because the z-index is same for both.
AC:
1. Actions Dropdown should be above response sort menu
2. Check if actions dropdown menu is above the header (for mobile view)
3. Make sure response sort popup is also responding in correct order (for mobile view)
|Before|After|
|<img width="410" alt="Screenshot 2023-04-18 at 12 49 22 PM" src="https://user-images.githubusercontent.com/72802712/232708961-1df70bcf-3e97-4b9d-807c-ecd36652855d.png"><img width="380" alt="Screenshot 2023-04-18 at 12 51 20 PM" src="https://user-images.githubusercontent.com/72802712/232709542-8a17b95b-6e83-40e7-8506-863bcf9f0535.png">|<img width="360" alt="Screenshot 2023-04-18 …

fix: action dropdown UI issues

---

package-lock.json
package.json

Reverts openedx/frontend-app-discussions#501
@UvgenGen I'm reverting this PR as it is failing stage build. frontend-platform v4.2.0 required node v18 and discussion MFE is using node v16. We can not upgrade to frontend-platform v4.2.0 until the discussion MFE node version is upgraded.

Revert "[FC-0014] update frontend-platform version to v4.2.0"

---

src/index.jsx

This PR enables react dev profiler on production to collect the performance data. This PR will revert after the data collection.

chore: enable profiler on production for data collection

---

src/index.jsx

This PR checks the react version on stage build. Currently react dev tool is not working and giving the error to use react 15+ and we are using react 16.14.

chore: console react version

---

src/index.scss

This PR fixes the postLink footer icon size. Currently, icon sizes are big on stage.
|Before|After|

fix: postLink footer icon size

---

package-lock.json
package.json

Updated frontend-platform version with GA4 implementation.
[FC-0014 - Google Analytics 4 Upgrade](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3668312128/FC-0014+-+Google+Analytics+4+Upgrade)

[FC-0014][olive] update frontend-platform version to v4.2.0

---

src/data/constants.js

Changes how the path are created for navigation. It will now use PUBLIC_PATH for path
Ticket; [INF-890](https://2u-internal.atlassian.net/browse/INF-890)
Tested locally by navigating to different routes

fix: switch to use PUBLIC_PATH for routes

---

src/discussions/comments/comment/CommentEditor.jsx
src/discussions/posts/post-editor/PostEditor.jsx

This is a backport from the [master](https://github.com/openedx/frontend-app-discussions/pull/513) and and this [PR](https://github.com/openedx/frontend-app-discussions/pull/533)
When trying to edit a post or comment, an error 400 occurred. Provided that the user is a course instructor or staff, and simultaneously the author of the post/comment.
The issue is the presence of the `editReasonCode` parameter in the request.
This parameter is expected only if the editor is not the author of the post/comment, and is a staff or instructor.
After the fixes, everything works correctly.

fix: 400 error editing posts and comment

---

src/discussions/post-comments/comments/comment/CommentEditor.jsx

This is a backport from the [master](https://github.com/openedx/frontend-app-discussions/pull/513) and and this [PR](https://github.com/openedx/frontend-app-discussions/pull/533)
When trying to edit a comment, an error 400 occurred. Provided that the user is a course instructor or staff, and simultaneously the author of the comment.
The issue is the presence of the `editReasonCode` parameter in the request.
This parameter is expected only if the editor is not the author of the comment, and is a staff or instructor.
After the fixes, everything works correctly.

fix: 400 error editing comment

---

src/discussions/post-comments/comments/comment/CommentEditor.jsx

When trying to edit a comment, an error 400 occurred. Provided that the user is a course instructor or staff, and simultaneously the author of the comment.
The issue is the presence of the `editReasonCode` parameter in the request.
This parameter is expected only if the editor is not the author of the post/comment, and is a staff or instructor.
After the fixes, everything works correctly.
NOTE: Similar changes were made to [fix the post editing error](https://github.com/openedx/frontend-app-discussions/pull/513).

fix: error 400  editing comment

---

README.rst

Codecov badge was using an old ref of code coverage which was getting report from edx. However, frontend-app-discussions have been moved under openedx namespace.  This PR updates the ref for codecov report.

chore: update codecov ref from edx to openedx

---

src/components/Search.jsx

An issue has been found with research if no changes are made to the search field:
- first search:
- second search:
This fix allows actions to be ignored if the current search query matches a previous query.
If there are any changes in the search query, then it is sent to the backend.

Fix bug with a repeated search query for Olive

---

src/components/Search.jsx

An issue has been found with research if no changes are made to the search field:
- first search:
- second search:
This fix allows actions to be ignored if the current search query matches a previous query.
If there are any changes in the search query, then it is sent to the backend.

Fix bug with a repeated search query  for Palm

---

src/components/Search.jsx

An issue has been found with research if no changes are made to the search field:
- first search:
- second search:
This fix allows actions to be ignored if the current search query matches a previous query.
If there are any changes in the search query, then it is sent to the backend.

Fix bug with a repeated search query

---

src/index.scss

- Add important in post type card border width which was overriding because of the paragon card class.

style: add important in post type card border

---

src/components/TinyMCEEditor.jsx

[INF-1033](https://2u-internal.atlassian.net/browse/INF-1033)
One of our partner’s has shared the following:
”When I've been testing out the discussion sidebar, when trying to add an image or code the modal that pops up is not actually visible, and requires scrolling to reach it. The post UI fades out like this with no indication that there's anything below it:
You then have to scroll down quite far to be able to add your image/code
Now for learning discussion side i fixed this issue by change the modal position from align center to align start.

fix: now discussion sidebar modal appears above the fold

---

Makefile
src/discussions/common/ActionsDropdown.jsx
src/discussions/common/Confirmation.jsx
src/discussions/common/HoverCard.jsx
src/discussions/data/hooks.test.jsx
src/discussions/data/selectors.js
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/discussions-home/DiscussionsRestrictionBanner.jsx
src/discussions/discussions-home/FeedbackWrapper.jsx
src/discussions/empty-posts/EmptyPosts.test.jsx
src/discussions/learners/LearnersView.jsx
src/discussions/post-comments/comments/CommentsView.jsx
src/discussions/post-comments/comments/comment/Comment.jsx
src/discussions/post-comments/comments/comment/Reply.jsx
src/discussions/posts/PostsList.jsx
src/discussions/posts/post-actions-bar/PostActionsBar.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post/LikeButton.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostFooter.jsx
src/discussions/tours/data/api.js
src/discussions/tours/data/thunks.js
src/i18n/index.js
src/index.scss

This will fix the Persian language code issue(fa-ir is the code in all of the other MFEs)
also fixed some typos in the code.

fix: Persian language

---

src/discussions/posts/post/PostLink.jsx

**Description** 
I noticed in Hotjar recordings that the “Load more posts” button is very slow and gets even slower with successive clicks. I’ve attached a recording of a test I conducted.
- First, load more clicks: API response takes 983 msec but it takes 6 seconds to load 10 new posts in the UI. :open_mouth:  
- 12th load more click: API response takes 816 msec but it takes 42 seconds to load 10 new posts in the UI. :exploding_head: It seems like the API call is sent 14 seconds after the button clicks.
https://www.loom.com/share/c2e296f135734a6389a238768d6e4602?sid=d0c0d7cb-7e9c-4cc5-b519-99c3c31bf9ad
**Implementation** 
- Component is optimized and every Post item is rendered one time. 
- The post item component was using the Truncate component to truncate the post title and preview. …

fix: resolved load more posts delay issue

---

src/components/NavigationBar/navBar.scss
src/index.scss

This pull request contains:
- a small fix for navigation container side indents and make them the same
- fix paragon and brand style imports (prepending module paths with a `~` tells webpack to search through node_modules)
PR to the open-release/palm.master branch: https://github.com/openedx/frontend-app-discussions/pull/599
PR to the master branch: https://github.com/openedx/frontend-app-discussions/pull/600
|Before|After|
|    ![image](https://github.com/openedx/frontend-app-discussions/assets/17108583/8d9e77af-b9e4-4a15-b47e-9e94c1ff833d)   |    ![image](https://github.com/openedx/frontend-app-discussions/assets/17108583/9ff83d1e-66e5-4992-8dd6-b5f8701daaba)  |

fix: container indents and style imports

---

src/discussions/common/AuthorLabel.jsx
src/discussions/common/EndorsedAlertBanner.jsx
src/index.scss

This pull request contains recommendations for fixing custom font-family and make it unified with all MFEs and Paragon components.
All MFEs must have the same default appearance and change them globally via `brand-openedx` component on demand.
PR to the open-release/palm.master branch: https://github.com/openedx/frontend-app-discussions/pull/596
PR to the open-release/quince.master branch: https://github.com/openedx/frontend-app-discussions/pull/597
|Before|After|
|   <img width="1727" alt="image" src="https://github.com/openedx/frontend-app-discussions/assets/17108583/1a3b047e-f973-43e3-9052-3bb1e90cd11a">   |   <img width="1727" alt="image" src="https://github.com/openedx/frontend-app-discussions/assets/17108583/c2535f55-d65a-4634-9b73-7a76312173f3"> |

fix: unify font-family with paragon component styles

---

src/discussions/posts/post/PostLink.jsx

**Description** 
I noticed in Hotjar recordings that the “Load more posts” button is very slow and gets even slower with successive clicks. I’ve attached a recording of a test I conducted.
- First, load more clicks: API response takes 983 msec but it takes 6 seconds to load 10 new posts in the UI. :open_mouth:  
- 12th load more click: API response takes 816 msec but it takes 42 seconds to load 10 new posts in the UI. :exploding_head: It seems like the API call is sent 14 seconds after the button clicks.
https://www.loom.com/share/c2e296f135734a6389a238768d6e4602?sid=d0c0d7cb-7e9c-4cc5-b519-99c3c31bf9ad
**Implementation** 
- Component is optimized and every Post item is rendered one time. 
- The post item component was using the Truncate component to truncate the post title and preview. …

fix: resolved load more posts delay issue (quince.master)

---

src/discussions/common/AlertBanner.jsx
src/discussions/common/AlertBanner.test.jsx
src/discussions/common/EndorsedAlertBanner.test.jsx
src/discussions/data/hooks.js
src/discussions/data/selectors.js
src/discussions/data/slices.js
src/discussions/post-comments/PostCommentsView.test.jsx
src/discussions/post-comments/comments/comment/CommentEditor.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post/Post.jsx

Deprecated enable_moderation_reason_codes flag from the discussion app
https://2u-internal.atlassian.net/browse/INF-1159

feat: removed enable_moderation_reason_codes flag

---

src/discussions/common/AuthorLabel.jsx
src/discussions/post-comments/comments/CommentsView.jsx
src/index.scss

- Fixed font family on page 
- Fixed borders on action bar on mobile view
- Fixed newest first text overlap another text
- Fixed displaying user name on mobile view

feat: Enhancements to page (palm.master)

---

src/index.scss

- Fixed editor bar visibility when scrolling up

feat: Editor bar visibility (quince.master)

---

src/index.scss

- Fixed editor bar visibility when scrolling up

feat: Editor bar visibility (palm.master)

---

src/discussions/common/AuthorLabel.jsx
src/discussions/common/AuthorLabel.test.jsx
src/discussions/data/hooks.js
src/discussions/data/selectors.js
src/discussions/data/slices.js
src/discussions/discussions-home/DiscussionSidebar.jsx
src/discussions/discussions-home/DiscussionsHome.jsx
src/discussions/discussions-home/DiscussionsHome.test.jsx
src/discussions/learners/LearnersView.jsx
src/discussions/learners/LearnersView.test.jsx
src/discussions/navigation/navigation-bar/NavigationBar.jsx
src/discussions/posts/post/PostLink.test.jsx

[INF-1185](https://2u-internal.atlassian.net/browse/INF-1185)
Removed `discussions.enable_learners_tab_in_discussions_mfe `dependency in MFE

chore: removed enable_learners_tab_in_discussions_mfe flag dependency

---

src/discussions/post-comments/comments/CommentsSort.jsx
src/discussions/posts/post-filter-bar/PostFilterBar.jsx
src/discussions/tours/DiscussionsProductTour.jsx
src/discussions/tours/constants.js
src/discussions/tours/messages.js

[INF-1172](https://2u-internal.atlassian.net/browse/INF-1172)
We have 2 product tours currently active:
- Unresponded filter in discussions
- Responses/comments sort in discussions
These features are not “new” especially to ~2000 users signing up daily. They have 3 more clicks to do before they can interact with discussions and the product tours may be somewhat distracting to a user. We need to deactivate all product tours that we created.

feat: removed sort and filter tour

---

src/components/FilterBar.jsx
src/discussions/learners/learner/LearnerFilterBar.jsx
src/discussions/posts/post-filter-bar/PostFilterBar.jsx

[INF-1096](https://2u-internal.atlassian.net/browse/INF-1096)
**Issue:** If filter menu is lengthy, selecting an option does not seem to have any impact, as seen in attached screen recording. Users will need to scroll down or close the menu to see the impact.
**Solution:** To remedy that, the filter menu is now collapsible  once an option has been selected.

fix: sort menu collapse after filter selection

---

src/discussions/posts/data/slices.js

Anonymous was visible in `My Post` when a new post was created as anonymous.  It automatically disappears on page refresh
Ticket: [INF-1232](https://2u-internal.atlassian.net/browse/INF-1232)
Tested by creating both anonymous and non-anonymous post. Anonymous posts are not visible in `My Post` on new post creation whereas non-anonymous post are visible.

fix: anonymous post should not be visible in my post

---

src/discussions/learners/learner-post-filter-bar/LearnerPostFilterBar.jsx

[INF-1236](https://2u-internal.atlassian.net/browse/INF-1236)
**Issue:**
The Learner Post filter is exhibiting unexpected behavior. When choosing the "unanswered" status, it should automatically switch the type filter to "question," and when selecting "not responded," it should switch to "discussion."
**Solution:**
The issue mentioned earlier has been resolved. Now, when the "unanswered" status is selected, the type filter automatically switches to "question," and when "not responded" is chosen, it switches to "discussion."

fix: fixed Learner Post filter issue

---

src/index.scss

[INF-891](https://2u-internal.atlassian.net/browse/INF-891)
**Explanation**
Styling for the code part of HTML has been added to prevent spilling out of the container.
**Before Change:**
**After Change:**

fix: updated css styling to prevent content spilling

---

Makefile
package-lock.json
package.json

Similar to https://github.com/openedx/frontend-app-learning/pull/1279
- install atlas
- remove `--filter` to pull all languages by default
- use ATLAS_OPTIONS to allow custom `--filter`
- include frontend-platform in `atlas pull`
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).

feat: tutor-mfe compatiblilty for `atlas pull` | FC

---

src/data/constants.js
src/discussions/common/AuthorLabel.jsx
src/discussions/common/AuthorLabel.test.jsx
src/discussions/messages.js
src/discussions/utils.js

[INF-737](https://2u-internal.atlassian.net/browse/INF-737)
Modified TA icons to include tool-tips and add a moderator label.
Corresponding backend PR: https://github.com/openedx/edx-platform/pull/34239
**Before**
https://github.com/openedx/frontend-app-discussions/assets/73840786/5c16727d-4241-446c-b2d0-b010e698d4ac
**After**
https://github.com/openedx/frontend-app-discussions/assets/73840786/c4babd29-0184-4981-a92b-97210de8c849

feat: modified TA icon according to role

---

src/components/PostPreviewPanel.jsx
src/discussions/discussions-home/DiscussionContent.jsx
src/discussions/posts/post/Post.jsx
src/index.scss

[INF-1148](https://2u-internal.atlassian.net/browse/INF-1148)
**Description
Issue**
Partner Support received a report that pasting Excel or CSV formatted tables works in preview mode when posting to the discussion forum, but the formatting gets stripped when the post is submitted, and looks disorganized in the live view.
**Solution**
Now table is showing properly in both preview and post lists
**Screenshots**
https://www.loom.com/share/1da9eed277024e34a13c673a91df6daa?sid=bf3eac06-8e00-49d5-b871-ff7fb8165adc

fix: table is now showing properly in preview and post lists

---

src/discussions/common/ActionsDropdown.jsx
src/discussions/post-comments/PostCommentsView.test.jsx
src/discussions/post-comments/comments/comment/CommentEditor.jsx

[INF-1158](https://2u-internal.atlassian.net/browse/INF-1158)
Currently, when clicking on the 'Add Response' button at the top right of the comment, the screen does not scroll to the input box. In scenarios where the response is too large, this behavior may give the impression that edX is not responding to the course team's action of creating a response. The suggestion is that when a user clicks on 'Add Response,' they should be directed directly to the end of the text, where the text field is visible.
https://www.loom.com/share/edf13a96bcb84512a3b725418c13cafd?sid=92841d71-8fec-4450-a41f-38b7fc65b883
https://www.loom.com/share/2dd82907f7904c6493807f67f83bda0a?sid=7a803fe7-5060-4564-945c-1d4cb0fe4506

feat: add auto scroll to editor functionality

---

src/discussions/posts/post-editor/PostTypeCard.jsx
src/index.scss

Backport from master - https://github.com/openedx/frontend-app-discussions/pull/640
When trying to post on the forum, the option to mark your post as “Discussion” or “Question” is not enabled
**Before fix**
**After fix**

fix: fixed post card border color issue (#640)

---

src/discussions/common/AuthorLabel.jsx
src/discussions/common/AuthorLabel.test.jsx

This is a backport from the master (https://github.com/openedx/frontend-app-discussions/pull/659)
Changes were cherry-picked from the master branch. 
The only difference is that `useShowLearnersTab` is still taken into account (depends on the `discussions.enable_learners_tab_in_discussions_mfe` waffle flag in the LMS, removed in master).
- fix: redirection to learners tab in inContext view. So a user can't navigate the site in the discussion sidebar <img width="1265" alt="image" src="https://github.com/openedx/frontend-app-discussions/assets/47273130/079668e5-4a6a-475c-bd6d-67023e4a446a">
- fix: changed username to simple text for in-context view
- test: username is not clickable in in-context view
- ensure the `discussions.enable_learners_tab_in_discussions_mfe` is enabled (you should …

[BACKPORT] fix: redirection to learners tab in inContext view

---

src/discussions/data/hooks.js
src/discussions/data/selectors.js
src/discussions/discussions-home/DiscussionsHome.jsx

[INF-1295](https://2u-internal.atlassian.net/browse/INF-1295)
Need following Improvements for the "Content Unavailable" Screen in the Discussion MFE and In-Context Sidebar.
**A.C**
1. Optimized API calls by restricted unnecessary parallel requests, only invoking the API returning the isEnroll attribute when needed, and prevented additional calls.
3. Ensured that unavailable content within the in-context sidebar remains hidden across all use cases.

feat: restricted unnecessary api calls

---

src/discussions/post-comments/data/slices.js

[INF-1285](https://2u-internal.atlassian.net/browse/INF-1285)
This PR fixes a Type error [prod-frontend-app-discussions]
`Error message: t.commentsInThreads[s] is not iterable `on new relic related to frontend change

fix: fixed commentsInThreads[s] is not iterable

---

src/discussions/post-comments/comments/comment/Reply.jsx

This merge request contains a fix for the comment edit block width at small screen resolutions for course Discussions pages or discussion sidebar in MFE Learning.
- quince branch: https://github.com/openedx/frontend-app-discussions/pull/705
- master branch: https://github.com/openedx/frontend-app-discussions/pull/706
|Before|After|
|  <img width="560" alt="image" src="https://github.com/openedx/frontend-app-discussions/assets/17108583/db0170cb-a46d-472d-9941-2013046013d6">    |    <img width="560" alt="image" src="https://github.com/openedx/frontend-app-discussions/assets/17108583/4c075157-28df-482b-8bca-138b160c0a20">  |

fix: block overflow when editing comment

---

src/discussions/common/HoverCard.jsx
src/discussions/posts/post/Post.jsx
src/discussions/posts/post/PostSummaryFooter.jsx
src/index.scss

A visual inconsistency was observed in the discussions sidebar. The font size appeared to be uneven or using different sizes for different elements within the sidebar which is fixe din this PR.
**Before** 
**After**

fix: fixed sidebar inconsistent font size

---

src/discussions/data/api.js
src/discussions/post-comments/PostCommentsView.test.jsx

The post editor is breaking for moderators, this was caused by the API being moved to v2 but due to implementation, 2 different APIs were using the same base URL method, which caused conflict in APIs. 
This issue is fixed by setting 2 different API  URL methods.
Tested with Staff, Moderator, and Learner role. 
1. Go to the discussions app from the user with a moderator. 
2. click on new post, it should work as expected.

fix: post editor breaking for moderator

---

src/discussions/common/HoverCard.jsx
src/discussions/data/hooks.js

[INF-1446](https://2u-internal.atlassian.net/browse/INF-1446)
Redwood branch fix
fix for https://github.com/openedx/frontend-app-discussions/issues/688
To prevent learners from accidentally voting on their own posts (previously possible), this frontend PR disables the like button for a learner's own posts.
https://github.com/openedx/edx-platform/pull/34993

fix: fixed author liking its own post

---

src/discussions/common/ActionsDropdown.jsx
src/discussions/data/selectors.js
src/discussions/post-comments/PostCommentsView.test.jsx
src/discussions/post-comments/comments/comment/CommentEditor.jsx
src/discussions/post-comments/data/hooks.js
src/discussions/post-comments/data/selectors.js
src/discussions/post-comments/data/slices.js
src/discussions/utils.js
src/setupTest.jsx

[INF-1444](https://2u-internal.atlassian.net/browse/INF-1444)
Learners using the discussion board have faced a frustrating issue: losing their work when switching tabs and returning to the post. This can be especially disheartening for those writing lengthy comments or responses. The issue occurs specifically while writing comments or responses on posts.
Solution 
Draft Feature: Offering a draft functionality where users can save unfinished posts and return to them later. The draft only be saved on the frontend and are lost on page reload.
https://www.loom.com/share/fa0007a967ea406f89835409009dd3b1?sid=72cdf8c3-2e9f-4816-ba62-d7b991b5872b

feat: added draft functionality for comment and responses

---

src/components/PostHelpPanel.jsx
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/posts/post-editor/PostEditor.test.jsx
src/discussions/posts/post-editor/messages.js
src/index.scss

[INF-821](https://2u-internal.atlassian.net/browse/INF-821)
To improve learner access to documentation about mathjax and forums in general, we introduced links to these docs within the text editor as show in option #7 of this mockup: [Discussions](https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=8264-311323&t=TZdvl2bN7uUYtzmO-4) and shown below.
Clicking on the “?” icon at the bottom right of the text editor will open a help menu. Users should be able to close it, similar to preview. 
Links to 2 docs will be shown initially, but more may be added later.
The “Participating in course discussions” will point to this link: [Participating in Course Discussions – edX Help Center](https://support.edx.org/hc/en-us/sections/115004169687-Participating-in-Course-Discussions) …

feat: added help section for post documentation

---

.github/workflows/ci.yml

This reverts commit dc5f097736d443dfb11a70ed3be694484319e4d9. Node 18 removal PRs should be merged after Sumac is cut.

Revert "test: Remove support for Node 18 (#736)"

---

README.rst

Ref https://github.com/openedx/docs.openedx.org/issues/955
This is the only instance I see in this repo.

docs: Update edx.rtd links to docs.openedx.org

---

package-lock.json
package.json
src/discussions/common/HoverCard.test.jsx
src/discussions/discussions-home/DiscussionsHome.test.jsx
src/discussions/empty-posts/EmptyTopics.test.jsx
src/discussions/in-context-topics/TopicPostsView.test.jsx
src/discussions/in-context-topics/TopicsView.test.jsx

Part 1 of https://github.com/openedx/frontend-app-discussions/issues/753

chore(deps): update `@openedx` dependencies to versions that support React 18

---

.gitignore
package-lock.json
package.json
src/discussions/discussions-home/DiscussionsHome.jsx
src/plugin-slots/FooterSlot/README.md
src/plugin-slots/README.md

https://app.pr-765-2977b1.sandboxes.opencraft.hosting/discussions/course-v1:demo+Course+1/posts

feat: import `FooterSlot` from component package instead of slot package

---

src/discussions/posts/data/hooks.js

This check for post fixes the issue that is caused in the new MFE discussion sidebar as mentioned in #751 
Before the change, I was seeing an error after creating a new post, but now it clears the current post data from the form and submits that.

Fix: error during post creation in discussion MFE sidebar (#751)

---

src/discussions/data/hooks.js
src/discussions/posts/post-editor/PostEditor.jsx
src/discussions/tours/constants.js
src/discussions/tours/messages.js

[INF-1930](https://2u-internal.atlassian.net/browse/INF-1930)
This PR introduces a product tour for the newly added “Notify all learners” checkbox in both the Discussions MFE and the Discussion Sidebar.
The product tour is designed to highlight and explain the new checkbox feature.
**Eligibility:** The tour will only be shown to users with roles that have permission to view the checkbox.
**Dismissal:** Once the user acknowledges the tour, it will not appear again.
**Content:**
**Title**: "Let your learners know."
**Body**: "Check this box to notify all learners."
**Feature Flag:**
The tour is gated behind the same waffle flag "notifications.enable_post_notify_all_learners" that controls the checkbox.

feat: added product tour to notify all learners

---

src/discussions/discussions-home/DiscussionSidebar.jsx

This PR fixes https://github.com/openedx/frontend-app-discussions/issues/703; this issue prevented users from going to the previous page when clicking the back button.
When the router ended at the fallback route, the browser history was contaminated with unnecessary logs; this merge request adds a `replace` prop in the `Navigate` component so this overrides the current route instead of creating a new one
Following the **Steps to reproduce** from the issue #703
|Before|After|
|[Screencast from 27-06-25 13:30:51.webm](https://github.com/user-attachments/assets/b99e0fa9-e219-43b0-b290-2b0e17e6d871)|[Screencast from 27-06-25 13:31:34.webm](https://github.com/user-attachments/assets/ce7e8a87-28a8-468c-ae73-893436532be3)|

fix: add replace prop to fallback route

---

src/discussions/common/AuthorLabel.jsx
src/discussions/messages.js

[INF-2069](https://2u-internal.atlassian.net/browse/INF-2069)
This PR adds a tooltip to display the logged-in user's course role (e.g., Instructor, Staff, Moderator) on posts, responses, and comments within the discussion forum.
The tooltip appears when hovering over the user’s name and provides additional context about their role in the course.

feat: added tooltip for author role

---

src/discussions/post-comments/comments/comment/CommentEditor.jsx
src/discussions/posts/post-editor/PostEditor.jsx

The rate limit dialogue should not be visible when editing content.

fix: fixed rate limit dialogue for edit contents

---

src/discussions/common/HoverCard.jsx
src/discussions/common/HoverCard.test.jsx

[INF-2096](https://2u-internal.atlassian.net/browse/INF-2096)
This PR enhances the forum menu by adding tooltips to the Like and Follow buttons. The tooltips provide quick contextual information for users, improving usability and accessibility.

feat: added tooltips for like and follow button

---

src/discussions/common/ActionsDropdown.jsx
src/discussions/common/ActionsDropdown.test.jsx
src/index.scss

Fixes the issue where the InContext Sidebar post menu dropdown was being forcefully contained within the sidebar container.  
This caused the dropdown to be clipped and introduced an unwanted scroll in the sidebar.
**2U Private Jira Ticket:** [LP-85](https://2u-internal.atlassian.net/jira/software/c/projects/LP/boards/3413/backlog?selectedIssue=LP-85)
---
- Verified locally in devstack by opening the InContext Sidebar and clicking the post menu (⋮).  
- Confirmed the dropdown opens correctly without clipping or sidebar scroll on different screen sizes.  
---

fix: resolve InContext Sidebar post menu dropdown clipping that triggered scroll
