openedx/frontend-app-discussions

src/discussions/posts/data/thunks.js, src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/topics/TopicsView.jsx
Typing into the  "Search all posts" box now works as intended, affecting the "My Posts" and "All Posts" lists.
Related tickets:
* [TNL-8428](https://openedx.atlassian.net/browse/TNL-8428)
* [BB-4418 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4418)
1. Open discussion MFE for demo course
2. Type into "Search all posts" box and press Enter
3. Verify that "All Posts" and "My Posts" lists only show matching posts.
=> [BD-38][TNL-8428] feat: Implement post search.

package-lock.json, package.json, src/discussions/comments/CommentsView.jsx, src/discussions/comments/comment-icons/CommentIcons.jsx, src/discussions/comments/messages.js, src/discussions/comments/reply/Reply.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/navigation/navigation-bar/NavigationBar.jsx, src/discussions/posts/post-filter-bar/PostFilterBar.jsx, src/discussions/posts/post/LikeButton.jsx, src/discussions/posts/post/Post.jsx, src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/messages.js, src/discussions/topics/topic-group/topic/Topic.jsx, src/discussions/topics/topic-search-bar/TopicSearchBar.jsx
This makes many tweaks to get the UI closer to
the mockup and using Paragon components as much as possible.
Related tickets:
* [TNL-8427](https://openedx.atlassian.net/browse/TNL-8427)
* [BB-4417](https://tasks.opencraft.com/browse/BB-4417)
Run the service and browse around?
=> [BD-38][TNL-8427] fix: Bring UI closer to mockups

package-lock.json, package.json, src/discussions/comments/CommentsView.jsx, src/discussions/comments/CommentsView.test.jsx, src/discussions/comments/data/redux.test.js, src/discussions/comments/data/selectors.js, src/discussions/comments/data/slices.js, src/discussions/comments/data/thunks.js, src/discussions/comments/messages.js, src/setupTest.js, src/store.js
This pull requests implements paging for post's comments.
When opening a post, initially only the comments from the first page are loaded. As long as there are more comments to load, a button for loading more comments will be visible.
The page size is not being passed to the backend, so it depends on the configuration/implementation of the API.
To be able to manually test the change you are going to need the following data setup in your devstack:
- A course
- At least two posts for this course
- More than 10 comments one of the posts (1 page is 10 comments)
The old UI can be used to setup the following data. Then you can go to `localhost:2002/discussions/<course_id>`. To get the course id, the URL of the old UI can be use, e.g. in …
=> feat: add comment pagination [BD-38] [TNL-8657] [BB-4735]

src/discussions/common/ActionsDropdown.jsx, src/discussions/common/ActionsDropdown.test.jsx, src/discussions/utils.js
This PR covers the ActionsDropdown component with behavior tests.
Tickets: [TNL-8696] [BB-4842]
=> test: add tests for ActionsDropdown [BD-38] [TNL-8696] [BB-4842]

src/discussions/comments/CommentsView.test.jsx, src/discussions/discussions-home/DiscussionsHome.test.jsx, src/discussions/topics/TopicsView.jsx
This PR adds tests boilerplate code and a single basic test for DiscussionsHome component.
=> test: add simple test for DiscussionsHome [BD-38] [TNL-8696] [BB-4842]

package-lock.json, package.json, src/components/TinyMCEEditor.jsx, src/discussions/posts/data/api.js, src/discussions/posts/data/api.test.js
Implement TinyMCE UI improvements as specified in [TNL-8779](https://openedx.atlassian.net/browse/TNL-8779)
Depends: https://github.com/edx/edx-platform/pull/29067
0. To test this, you'll need:
* A running devstack
* A course, such as the Demonstration Course automatically created by the devstack.
1. Access the discussions application through the link: `http://localhost:2002/discussions/<course_id>`. If using the default demonstration course, the full link for it will be http://localhost:2002/discussions/course-v1:edX+DemoX+Demo_Course.
2. Click the `Add a post` button.
* The toolbar should include the requested buttons.
* Opening the formatting menu or the image and code dialogs should appear with the correct background color, and not transparent.
* The auto-save feature should store a …
=> feat: TinyMCE improvements [BD-38] [TNL-8779] [BB-4961]

src/discussions/topics/TopicsView.jsx, src/discussions/topics/TopicsView.test.jsx, src/discussions/topics/data/__factories__/index.js, src/discussions/topics/data/__factories__/topics.factory.js, src/discussions/topics/topic-group/TopicGroup.jsx
This PR covers TopicsView component with behavior tests.
=> test: add tests for TopicsView component [BD-38] [TNL-8696] [BB-4842]

src/discussions/data/api.js, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/data/thunks.js, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/navigation/navigation-bar/NavigationBar.jsx, src/discussions/navigation/navigation-bar/messages.js, src/discussions/posts/data/api.js, src/discussions/posts/data/thunks.js, src/discussions/posts/post-editor/PostEditor.jsx, src/discussions/posts/post-editor/messages.js, src/discussions/posts/post/PostHeader.jsx, src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/messages.js, src/store.js
Hooks up the configuration API to allow posting threads anonymously.
=> feat: add support for anonymous posting [BD-38] [TNL-9224]

package-lock.json, package.json, src/components/TinyMCEEditor.jsx, src/discussions/data/__factories__/config.factory.js, src/discussions/data/__factories__/index.js, src/discussions/data/__factories__/settings.factory.js, src/discussions/data/api.js, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/data/thunks.js, src/discussions/posts/data/api.js, src/discussions/posts/post-editor/PostEditor.jsx, src/discussions/posts/post-editor/PostEditor.test.jsx, src/discussions/posts/post-editor/messages.js, src/discussions/topics/data/selectors.js
Uses the discussions settings API to fetch course division configuration and makes the cohort selection dynamic based on if a topic is divided.
=> feat: Fully implements support for cohorts [BD-38] [TNL-9304]

src/components/TinyMCEEditor.jsx, src/discussions/comments/comment/CommentEditor.jsx, src/discussions/posts/post-editor/PostEditor.jsx
Fixes autosaving by adding an explicit ID so that autosaves are scoped correctly.
=> fix: fix autosaving  [BD-38] [TNL-9303]

src/discussions/comments/data/redux.test.js, src/discussions/comments/data/slices.js
This PR fixes the issue with paginating after posting a new comment or response, where the newly posted comment would be left behind the page of older comments that was loaded. This also fixes the duplication issue when paginating to the end, as the new comment would also be appended again when returned from the API.
1. Create a Post
2. Add a few comments to the Post, enough to require pagination (more than 10).
3. Reload the page, so that the Load More button is visible
4. Post a new Comment, and verify it has been appended to the end of the currently visible comments.
5. Click the Load More button
6. Verify that the page has been loaded before the new comment, and that there's no duplicate.
7. Repeat with responses to one of the comments.
=> [BD-38] [TNL-8657] [BB-5007] Fix load more comments with new comment

package-lock.json, package.json, src/index.jsx, src/index.scss
[TNL-9543](https://openedx.atlassian.net/browse/TNL-9543)
- Remove unnecessary header and footer dependency after deleting the header and footer component from the MFE.
=> chore: remove edx header and footer dependency

public/index.html, src/discussions/discussions-home/DiscussionsHome.jsx
Adds independent scrolling for left and right panels.
=> feat: independent scrolling for posts list and posts [BD-38] [TNL-9571] 

src/discussions/posts/post/PostFooter.jsx
Added a check while displaying the message icon for comments if comments count is great than 1.
https://openedx.atlassian.net/browse/TNL-9570
=> [TNL-9570] Message icon showing in the absense of comments or responses on the post.

public/index.html
TNL TICKET: https://openedx.atlassian.net/browse/TNL-9644
This is the quick fix PR for testing the resolution of zoomed-in behavior on stage environment as I am unable to set theme using local development.
=> style: small class added to fix UI zoomed in behavior

src/discussions/posts/post-actions-bar/PostActionsBar.jsx
follow up PR for [tnl-9644](https://openedx.atlassian.net/browse/TNL-9644) 
A PR has alread been merged #77
=> search bar and add post button fix

src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/posts/post-actions-bar/actionBar.scss, src/discussions/posts/post-editor/PostEditor.jsx
follow up PR for [tnl-9644](https://openedx.atlassian.net/browse/TNL-9644) 
A PR has already been merged #77 and #79
=> style: action bar and radio button fixes

src/discussions/comments/CommentsView.jsx, src/discussions/comments/messages.js, src/discussions/posts/post-editor/PostEditor.jsx
TNL Tickets: 
[TNL-9614](https://openedx.atlassian.net/browse/TNL-9614)
[TNL-9612](https://openedx.atlassian.net/browse/TNL-9612)
card component will show selection cursor pointer when hovered 
distinction between endorsed/unendorsed response counts removed
=> Discussion MFE fixes [TNL-9614] [TNL-9612]

src/discussions/comments/comment/CommentHeader.jsx, src/discussions/comments/comment/CommentHeader.test.jsx
Show the CheckCircle icon for posts which are marked as answers and show
the Verified badge icon for discussion posts marked as endorsed.
- https://openedx.atlassian.net/browse/TNL-9611
=> [BD-38] [TNL-9611] [BB-5606] Show check icons for endorsed posts

package-lock.json, package.json, src/discussions/posts/post-editor/PostEditor.jsx
TNL Ticket: https://openedx.atlassian.net/browse/TNL-9682
Card Component had some breaking changes in the latest paragon version, the changes are handled in this PR as well.
Screen recording to show hover effect which is fixed by paragon version upgrade
https://user-images.githubusercontent.com/67791278/157454026-65054bd1-cd66-4b2f-8a1d-80a42b317b95.mov
=> chore: update paragon version to 19.6.0

src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/PostLink.test.jsx, src/discussions/posts/post/messages.js
https://openedx.atlassian.net/browse/TNL-9648
Before
After
=> fix: report indicator showing different on post summary

src/discussions/posts/PostsView.jsx
https://openedx.atlassian.net/browse/TNL-9681
Before
After
=> fix: posts not loading when scrolled to bottom

src/discussions/comments/CommentsView.test.jsx, src/discussions/comments/comment/Comment.jsx, src/discussions/comments/comment/CommentEditor.jsx, src/discussions/comments/data/api.js, src/discussions/comments/data/redux.test.js, src/discussions/comments/messages.js, src/discussions/common/AlertBanner.jsx, src/discussions/common/AlertBanner.test.jsx, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.test.jsx, src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx, src/discussions/posts/data/api.js, src/discussions/posts/data/redux.test.js, src/discussions/posts/data/thunks.js, src/discussions/posts/post-editor/PostEditor.jsx, src/discussions/posts/post-editor/PostEditor.test.jsx, src/discussions/posts/post-editor/messages.js, src/discussions/posts/post/Post.jsx, src/discussions/posts/post/messages.js
[x] Add selector for edit reason codes on post and comment editing
[x] Add indicator in the posts list that the post was edited by a moderator
[ ] Add tests
=> [BD-38] [TNL-9266] [BB-5143] Add reason code selection UI for moderators on posts

src/components/TinyMCEEditor.jsx
**Supporting information**
- https://openedx.atlassian.net/browse/TNL-5596
- https://tasks.opencraft.com/browse/BB-5596
**Testing instructions**
- Start the DevStack
- Start the Frontend-app-discussions app
- Log in as any user who can create a post/comment and hit `Add a post` button 
- Start writing some content to the text area.
=> fix: [BD-38] [TNL-5596][BB-5596] Fix TinyMCE padding

src/discussions/posts/post/PostFooter.jsx, src/discussions/posts/post/PostFooter.test.jsx
Description
Fix Fellow button on post summary:
**Supporting information**
- https://openedx.atlassian.net/browse/TNL-9629
- https://tasks.opencraft.com/browse/BB-5599
** Fixed issue **
https://www.loom.com/share/729bba1222e44004b678d2d6665a3477
=> fix: [BD-38] [BB-5599] [TNL-9629] fix `Follow` button on post summary

src/discussions/comments/CommentsView.jsx, src/discussions/comments/messages.js
Ticket: [TNL-9612](https://openedx.atlassian.net/browse/TNL-9612)
Manually reverted changes in TNL-9612
=> fix: revert for TNL-9612

src/data/constants.js, src/discussions/common/context.js, src/discussions/data/hooks.js, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/discussions-home/DiscussionSidebar.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/learners/LearnersView.test.jsx, src/discussions/learners/data/__factories__/index.js, src/discussions/learners/data/__factories__/learners.factory.js, src/discussions/learners/data/api.js, src/discussions/learners/data/index.js, src/discussions/learners/data/selectors.js, src/discussions/learners/data/slices.js, src/discussions/learners/data/thunks.js, src/discussions/learners/index.js, src/discussions/learners/learner/LearnerAvatar.jsx, src/discussions/learners/learner/LearnerCard.jsx, src/discussions/learners/learner/LearnerFooter.jsx, src/discussions/learners/learner/LearnerFooter.test.jsx, src/discussions/learners/learner/index.js, src/discussions/learners/learner/messages.js, src/discussions/learners/learner/proptypes.js, src/discussions/navigation/navigation-bar/NavigationBar.jsx, src/discussions/navigation/navigation-bar/messages.js, src/store.js
Add Learners tab and list.
**Supporting information**
https://openedx.atlassian.net/browse/TNL-8841
https://tasks.opencraft.com/browse/BB-5013
** Feature **
https://www.loom.com/share/9927fffb31e543e49f4b08c989e56784
=> feat: [BD-38] [BB-5013] Add Learners list

src/discussions/posts/post/LikeButton.jsx
Fixed spacing of likes count
Ticket Link: https://openedx.atlassian.net/browse/TNL-9741
Before:
After:
=> fix: add spacing to likes count

src/discussions/discussions-home/DiscussionSidebar.jsx, src/discussions/discussions-home/DiscussionSidebar.test.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/data/thunks.js
[TNL-9744](https://openedx.atlassian.net/browse/TNL-9744)
- All post tab will be selected and loaded by default.
- There would be not repeated post summaries in post sidebar. 
https://www.loom.com/share/cacd53007d47411a852d9cf9403c6837
=> fix: post summaries are being repeated in the list

src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/discussions-home/DiscussionsHome.scss
[TNL-9693](https://openedx.atlassian.net/browse/TNL-9693)
- Fix Navbar bottom shadow
Fix
Figma
=> fix: navbar shadow

src/discussions/posts/post/PostLink.jsx
color contrast improved for unread posts
=> fix: color contrast improved for unread posts

src/discussions/common/ActionsDropdown.test.jsx, src/discussions/discussions-home/DiscussionsHome.test.jsx, src/discussions/posts/post-actions-bar/PostActionsBar.jsx
Use postmessage-based API to send message to close learning MFE sidebar.
=> feat: Add support for closing in-context sidebar [BD-38] 

src/discussions/data/hooks.js, src/discussions/data/hooks.test.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/utils.js
Sends the current path to the learning MFE, so it can maintain the path on reload.
=> feat: send message to learning MFE on navigation [BD-38] [TNL-9585]

package-lock.json, package.json
frontend build test fix for stage adding frontend build dependency in dependencies object.
=> fix: frontend build test fix for stage

.gitignore
revert to node 12 to test build issue
=> revert: revert to node 12 to test build issue

.gitignore
Reverts openedx/frontend-app-discussions#133
=> Revert "revert: downgraded node to 12 again to resolve build issue"

package-lock.json, package.json
Reverts openedx/frontend-app-discussions#126
=> Revert "fix: frontend build test fix for stage"

src/discussions/posts/post/PostFooter.jsx, src/discussions/posts/post/PostLink.jsx
Updated post summary design
Ticket:
https://openedx.atlassian.net/browse/TNL-9851
Before
After
=> fix: updated post summary design

src/discussions/posts/post/ClosePostReasonModal.jsx
https://user-images.githubusercontent.com/118837/161963201-0f107f6e-d40c-43e6-933f-d3201e23bf71.mp4
=> fix: scroll the post close dialog into view when it appears [BD-38] [TNL-9810]

src/discussions/comments/data/api.js, src/discussions/learners/LearnersContentView.test.jsx, src/discussions/learners/data/api.js, src/discussions/learners/data/selectors.js, src/discussions/learners/data/slices.js, src/discussions/learners/data/thunks.js, src/discussions/learners/learner/CommentsTabContent.jsx, src/discussions/learners/learner/LearnerFooter.jsx, src/discussions/learners/learner/PostsTabContent.jsx, src/discussions/learners/learner/messages.js, src/discussions/posts/data/api.js
Adds support for pagination on the learners page, including the learners list, the post, comments and responses lists.
=> feat: add support for pagination on learner page [BD-38] [TNL-9844]

src/components/TinyMCEEditor.jsx
Frontend PR for ticket 
https://openedx.atlassian.net/browse/INF-41
=> fix: hyperlinks opening in current tab

src/discussions/learners/data/slices.js
Loading symbol exists even after successful load
Ticket Link
https://openedx.atlassian.net/browse/INF-181
=> fix: loading symbol remains after successful

src/data/redux.test.js, src/discussions/learners/LearnersContentView.test.jsx, src/discussions/posts/PostsView.test.jsx, src/discussions/posts/post-filter-bar/PostFilterBar.jsx, src/discussions/utils.js
Allow using the unread filter with questions.
=> fix: Don't force unread view to only discussions [BD-38] [INF-129]

src/components/icons/Help.js, src/components/icons/index.js, src/data/constants.js, src/discussions/common/AuthorLabel.jsx, src/discussions/common/time-locale.js, src/discussions/posts/post/LikeButton.jsx, src/discussions/posts/post/PostFooter.jsx, src/discussions/posts/post/PostFooter.test.jsx, src/discussions/posts/post/PostHeader.jsx, src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/messages.js, src/index.scss
Ticket
https://2u-internal.atlassian.net/browse/INF-211
Figma
Current
=> fix: updated post summary

src/discussions/common/AuthorLabel.jsx, src/discussions/posts/post/PostHeader.jsx, src/discussions/posts/post/PostLink.jsx, src/index.scss
=> fix: post summary ui update

package-lock.json
The build is failing with a webpack issue on stage `lockfile` is regenerated to fix the build issue.
=> fix: lockfile regenerated to fix build issue

package-lock.json
Reverts openedx/frontend-app-discussions#169
=> Revert "fix: lockfile regenerated to fix build issue"

src/discussions/posts/post-editor/PostEditor.jsx
This is a temporary change that will be reverted in the following PR to deploy needed fixes on production which this change is blocking. this is required however on the stage environment for partner support testing and feedback.
=> temp: post preview removed temporarily to move fixes on prod

src/discussions/posts/post-editor/PostEditor.jsx
Adding post preview back to deploy on stage.
=> Revert "temp: post preview removed temporarily to move fixes on prod"

src/discussions/posts/post-editor/PostEditor.jsx
Ticket:
https://2u-internal.atlassian.net/browse/INF-167
In MFE, the user was not following the post he created.
=> fix: following the post while creating

src/discussions/discussions-home/DiscussionSidebar.test.jsx, src/discussions/posts/PostsView.test.jsx, src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/messages.js, src/discussions/utils.js
Ticket Link
https://2u-internal.atlassian.net/browse/INF-283
It will now show "No preview available" message if preview has image or mathjax expression
=> fix: show no preview avaiable if preview has image or mathjax

package-lock.json
Reverts openedx/frontend-app-discussions#190
=> Revert "chore: generate new package-lock"

src/discussions/posts/PostsView.jsx, src/discussions/posts/post/PostHeader.jsx, src/discussions/posts/post/PostLink.jsx
- addressed accessibility issues in this PR to make content structure meaningful
- assigned roles to items to give semantic meanings
=> fix: accessibility issues

src/discussions/discussions-home/DiscussionSidebar.test.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/PostsView.test.jsx, src/discussions/posts/post-filter-bar/PostFilterBar.jsx
https://2u-internal.atlassian.net/browse/INF-305
1. Fixed reported filter is now visible to global admin.
2. In the case of reported nested comment/content Post was not showing a reported tag. It is also fixed by this change.
=> fix: Reported filter for global admin

src/discussions/common/AlertBanner.jsx, src/discussions/common/AuthorLabel.jsx, src/discussions/discussions-home/DiscussionSidebar.test.jsx, src/discussions/learners/LearnerPostsView.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/learners/data/api.js, src/discussions/learners/data/selectors.js, src/discussions/learners/data/thunks.js, src/discussions/posts/PostsList.jsx, src/discussions/posts/data/selectors.js, src/discussions/posts/data/slices.js, src/discussions/posts/post/PostLink.jsx, src/discussions/posts/post/PostLink.test.jsx
1. Click on post summery card username will redirect to the user all created and interacted posts under the learner tab.
=> feat: clickable username in post summery card

src/components/Search.jsx, src/components/SearchInfo.jsx, src/components/index.js, src/discussions/posts/PostsView.jsx, src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/posts/post-actions-bar/messages.js, src/discussions/topics/TopicsView.jsx, src/discussions/topics/data/slices.js, src/discussions/topics/topic-group/LegacyTopicGroup.jsx, src/discussions/topics/topic-group/TopicGroupBase.jsx, src/discussions/topics/utils.js
All searches to be initiated from the same search bar. 
== Edit
Search was not working for topics as intended. 
Ticket:
https://2u-internal.atlassian.net/browse/INF-251
=> feat: update search in discussions mfe

src/components/Search.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/learners/data/selectors.js, src/discussions/learners/data/slices.js, src/discussions/learners/data/thunks.js
Add Search functionality to the new Search Component for partial username search on Learners Tab.
=> fix: add learner partial username search functionality to the new search component

src/discussions/posts/PostsList.jsx
Ticket:
https://2u-internal.atlassian.net/browse/INF-362
No results will be shown after API call is completed
=> fix: no results found should be displayed afer api call

src/discussions/comments/CommentsView.jsx, src/discussions/comments/comment/Comment.jsx, src/discussions/comments/comment/Reply.jsx, src/discussions/comments/messages.js
Ticket ID: https://2u-internal.atlassian.net/browse/INF-333
DOM PRINT AFTER FIX
- heading moved up 
- no interstitial divs between list items
- list / list items roles added for nested list items
- sr only description added for replies to response comments.
=> fix: accessibility fix added for the threads section

src/discussions/posts/post/PostLink.jsx
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-354
=> fix: updated pinned post icon

src/components/icons/PushPin.jsx, src/components/icons/index.js, src/discussions/posts/post/PostLink.jsx
Added PushPin icon to mfe
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-354
=> fix: added pushpin icon to mfe

src/components/Search.jsx
Replaced clear button with search button on search bar.
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-396
=> feat: added search button in place of clear button

.tx/config, Makefile, package-lock.json, package.json
Setup **Transifex** for `frontend-app-discussions repo`.
=> feat: add transifex configuration to allow translation jobs.

src/discussions/common/AlertBanner.jsx, src/discussions/data/hooks.js
- Display post closed/edited reason to post author or privileged users
=> fix: display post closed/edited reason to post author

src/discussions/learners/LearnersView.test.jsx, src/discussions/learners/learner/LearnerCard.jsx
https://2u-internal.atlassian.net/browse/INF-427
- last login time is hidden from FE and will be added back once we have an actual time of last activity on forum starts returning.
=> fix: last login time is hidden from FE

src/discussions/comments/CommentsView.jsx, src/discussions/comments/CommentsView.test.jsx, src/discussions/comments/comment/ResponseEditor.jsx
https://2u-internal.atlassian.net/browse/INF-407
> @mehaknasir Button's top/ bottom margin is not matching with Figma. Please match it from Figma.
fixed it ss attached
=> fix: add a response button added at the end of thread

.eslintrc.js, src/discussions/learners/LearnerPostsView.jsx, src/discussions/learners/learner/LearnerFilterBar.jsx, src/discussions/posts/PostsList.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/post-filter-bar/PostFilterBar.jsx, src/discussions/posts/post/PostLink.jsx, src/index.scss
https://2u-internal.atlassian.net/browse/INF-280
https://2u-internal.atlassian.net/browse/INF-408
- sidebar post list can be navigated using up or down arrow keys.
- filter menu has now grey background color on focus within to show the focused state.
=> fix: accessibility fixes

src/components/Search.jsx, src/components/SearchInfo.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/posts/NoResults.jsx, src/discussions/topics/TopicsView.jsx
- Added NoResults to Topics and Learners tab
- Added SearchInfo to Learners tab
- Hide filter bar when user searches in Learners tab
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-412
https://2u-internal.atlassian.net/browse/INF-414
=> fix: added no results bar to topics tab and search info to learners tab

src/index.scss
Fix header and footer styling issues.
=> fix: fix styles for header and footer

src/components/PostPreviewPane.jsx, src/discussions/posts/post-editor/PostEditor.jsx, src/index.scss
These issues have been resolved in this PR.
- Post form alignment and padding
- Post type box width 
- Post type icon color 
- Post type box text color and shadow
- Post Title input width
- Show Preview button alignment
- Spacing between fields
=> fix: style issues for new post and edit post form

src/discussions/comments/comment/Reply.jsx, src/discussions/comments/messages.js, src/discussions/common/EndorsedAlertBanner.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/posts/post/PostLink.jsx
This PR resolved these issues.
- Remove Reply box rounded border
- Convert Endorsed and answered time into a single character
- Question Post avatar position is misplaced in the post summary list after pinned post.
=> fix: response and comment UI

src/discussions/comments/comment/ResponseEditor.jsx
Jonathan feedback handled in this PR
=> fix: style issues in add response bottom section

src/discussions/data/hooks.js
- Discussion MFE desktop screen is creating a responsiveness issue in an iframe. Iframe considers desktop screen to tablet screen.
=> fix: desktop responsiveness issue

src/discussions/learners/data/selectors.js, src/discussions/learners/learner/LearnerAvatar.jsx, src/discussions/learners/learner/LearnerCard.jsx
This PR contains the following fixes.
- Avatars are appearing pixellated/blurry
- Remove the shaded hover state color
https://2u-internal.atlassian.net/browse/INF-383
=> fix: Resolved UI issues in learners tab

src/components/SearchInfo.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/post-actions-bar/messages.js, src/discussions/topics/TopicsView.jsx
Show "Searching..." when API call is in progress
Ticket Link
https://2u-internal.atlassian.net/browse/INF-456
=> fix: show searching when api call is in progress

src/components/Search.jsx, src/discussions/utils.js, src/index.scss
- Changed reported icon according to figma
- Pointer icon when hover on search icon
- Dont search if search field is blank
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-391
https://2u-internal.atlassian.net/browse/INF-409
https://2u-internal.atlassian.net/browse/INF-410
=> fix: updated reported icon and search bar

src/components/SearchInfo.jsx, src/discussions/messages.js, src/discussions/posts/NoResults.jsx
Updated design as per figma mockup
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-412
=> fix: updated search info and no result design

src/discussions/common/AuthorLabel.jsx, src/discussions/data/hooks.js, src/discussions/data/selectors.js, src/discussions/discussions-home/DiscussionSidebar.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/navigation/navigation-bar/NavigationBar.jsx
- learner tab will not be visible to student roles 
- learners won't be able to access it through URL as well
=> fix: learner tab is hidden from learners

src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.jsx
Fixed hash displaying as %23
Ticket link:
https://2u-internal.atlassian.net/browse/INF-468
=> fix: hash displaying as encoded

src/discussions/comments/CommentsView.jsx
https://2u-internal.atlassian.net/browse/INF-443
Add response button will be visible only once in the comments section.
=> fix: add response duplication button fixed

src/components/icons/InsertLink.jsx, src/components/icons/index.js, src/discussions/utils.js
=> fix: added insertlink icon

src/discussions/data/thunks.js, src/discussions/discussions-home/DiscussionSidebar.jsx
https://2u-internal.atlassian.net/browse/INF-512
- all types of users will land on the All Posts tabs by default
- Default reported filter is removed from landing logic for privileged users.
=> fix: fixed landing url and filters

src/discussions/discussions-home/InformationBanner.test.jsx, src/discussions/discussions-home/InformationsBanner.jsx
-code updated on stage and found out that user which is admin and has only student role in role_set is shown learners feedback form.
=> fix: admin form fix

src/discussions/comments/CommentsView.jsx
Reverts openedx/frontend-app-discussions#283
=> Revert "fix: add response duplication button fixed"

src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/discussions-home/InformationsBanner.jsx
=> style banner design fix

src/index.scss
Match discussions header with learning MFE header
Ticket
https://2u-internal.atlassian.net/browse/INF-501
Sample output
=> fix: match discussion header with learning header

package-lock.json, package.json, src/index.jsx
- Configure breaking change related to paragon's messages intl.
- Test all the UI components
=> chore: upgrade paragon version to 20.11.1

src/index.scss
Updated UI design of discussions header to match with learning header
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-501
=> fix: updated header and navigation bar UI

package-lock.json, package.json, src/index.jsx
revert #296 
The upgrade has conflicted with the actions menu dropdown will look for a fix for the actions menu first and upgrade paragon later.
CC: @awais-ansari @asadazam93 
before downgrade
after downgrade:
=> revert: paragon downgraded to avoid action menu placement issue

src/discussions/comments/CommentsView.jsx
Removed responses sort from frontend
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-546
=> fix: removed responses sort from frontend

src/discussions/posts/PostsView.jsx, src/discussions/posts/post-actions-bar/messages.js, src/discussions/posts/post-filter-bar/PostFilterBar.jsx, src/discussions/topics/messages.js, src/discussions/topics/topic-search-bar/TopicSearchBar.jsx
- Search learners text fixed
- Search topics text fixed
- show **all posts** instead of **own post** in my posts tab
=> fix: ui text changes

src/components/TinyMCEEditor.jsx, src/discussions/comments/comment/CommentEditor.jsx, src/discussions/posts/post-editor/PostEditor.jsx, src/index.scss
- Text Editor will reset to the initial value then click on submit and cancel button while creating the post.
- Text Editor will reset to the initial value then click on submit and cancel button while creating the Response/Comment.
- Text Editor will not persist the text.
https://www.loom.com/share/896bd04092c1422aa864a8cd64e6256e
=> fix: remove editor text persistence

package-lock.json, package.json, src/discussions/common/ActionsDropdown.jsx, src/index.jsx, src/index.scss
- Upgrade the paragon version to 20.12.1
- Fix the action menu modal position issue 
- Fix action menu modal and header overlapping
- The UI is working fine after the upgrade
https://www.loom.com/share/452dfb5bc4d6440fb2b7e260650b4eac
=> chore: upgrade paragon version to 20.12.1

src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/discussions-home/DiscussionsHome.test.jsx
Removed support for discussions mfe rendering in iframe
Ticket Link:
https://2u-internal.atlassian.net/browse/INF-337
Backend PR:
https://github.com/openedx/edx-platform/pull/31067
=> feat: remove support for discussion mfe in iframe

src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.jsx, src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/post/PostLink.jsx, src/discussions/topics/TopicsView.jsx, src/discussions/topics/TopicsView.test.jsx, src/discussions/topics/messages.js, src/discussions/topics/topic-group/TopicGroupBase.jsx, src/discussions/topics/topic-group/topic/Topic.jsx, src/index.scss
- Update Topic list, icons, text color, divider color and height, border, and hover states
- Add box-shadow on the topic breadcrumb bar
https://www.loom.com/share/55147f9c49d8469c9552647140f0cb37
=> fix: update topics listing UI

src/components/SearchInfo.jsx, src/discussions/posts/PostsView.jsx, src/discussions/posts/data/slices.js, src/discussions/posts/data/thunks.js, src/discussions/posts/post-actions-bar/messages.js
Ticket: https://2u-internal.atlassian.net/browse/INF-552
search rewrite info
search info
=> fix: text search rewrite text added

public/index.html
- Remove the horizontal scrollbar from Discussion MEF
=> fix: remove horizontal scrollbar

public/index.html, src/discussions/comments/comment/Comment.jsx, src/discussions/comments/comment/CommentEditor.jsx, src/discussions/posts/post-editor/PostEditor.jsx
- Global staff can edit post/comment/reply
- Global staff change edit reason while editing the post/comment
https://www.loom.com/share/5ffb0716c0604a80b9efe19989afbf00
https://www.loom.com/share/9c4e0f98847d409bb636f28c9949a8fe
=> fix: add violates-guidelines edit reason as a default value for global staff

src/discussions/discussions-home/DiscussionSidebar.jsx
- Replace body height with paragon windowSize hook in sidebar dynamic calculation
- body height was not consistent which may be cause the issue in calculation
=> fix: replace body height with paragon windowSize

src/discussions/learners/LearnerPostsView.jsx, src/discussions/learners/LearnerPostsView.test.jsx, src/discussions/learners/data/__factories__/learners.factory.js, src/discussions/learners/data/api.js, src/discussions/learners/data/thunks.js
Learners area post summary will show reported marker if any comment is reported
Ticket link:
https://2u-internal.atlassian.net/browse/INF-365
=> feat: learners area post summary will show reported if any comment is reported

src/components/PostPreviewPane.jsx, src/components/TinyMCEEditor.jsx, src/discussions/common/AuthorLabel.jsx
- Add auto resize plugin in TinyMCE
- Editor will resize according to content in post/comment/response
- Preview will resize according to content in the post/comment/response
https://www.loom.com/share/8b4039f4276b402eb75cbc61a06bf3f1
https://www.loom.com/share/7928c66f102c46d3b6ef55ae523baa3f
=> fix: add autoresize plugin in TinyMCE editor

src/discussions/posts/post-actions-bar/PostActionsBar.jsx
[INF-622](https://2u-internal.atlassian.net/browse/INF-622)
Courses with active discussion blackout dates does not load Add a Post button
**Before fix**
[25c75cc7-ab4d-470f-a11e-7ae02bd7ae24.webm](https://user-images.githubusercontent.com/73840786/201908282-ffbf6d8c-ed21-4af9-9e5f-e696691c2a4b.webm)
**After fix**
[d9064e90-a08a-4d56-9ad3-0b653f5f36cb.webm](https://user-images.githubusercontent.com/73840786/202164084-8f0f1c88-8849-4fb5-8ff1-569fa2362c4e.webm)
=> fix: active discussion blackout dates does not load add a post button

src/discussions/posts/post/PostLink.jsx
[INF-634](https://2u-internal.atlassian.net/browse/INF-634)
Before : 
After: 
Figma:
=> style: fixed text truncate for title

src/components/FilterBar.jsx, src/discussions/learners/messages.js, src/discussions/posts/PostsView.test.jsx, src/discussions/posts/post-filter-bar/messages.js
1. Update most votes filter name to most likes
2. Add a sorted word in the filter description for sorting options
1 <img width="477" alt="Screenshot 2022-11-22 at 9 23 03 PM" src="https://user-images.githubusercontent.com/79941147/203367309-39bb0880-8ca2-43aa-830c-116f0f87de5a.png">
2 <img width="475" alt="Screenshot 2022-11-22 at 9 43 00 PM" src="https://user-images.githubusercontent.com/79941147/203371782-5a941292-a3b2-42a2-8dea-84b4e079877b.png">
2 <img width="477" alt="Screenshot 2022-11-22 at 9 43 07 PM" src="https://user-images.githubusercontent.com/79941147/203371786-b4781252-6d61-46e2-8239-470e691e6745.png">
1 <img width="471" alt="Screenshot 2022-11-22 at 9 41 50 PM" src="https://user-images.githubusercontent.com/79941147/203371445-aeccf08b-9395-4a2f-892f-cc6bbc8d9d32.png">
2 …
=> fix: minor issue after MEF rollout

src/discussions/comments/comment/Comment.jsx
[INF-666](https://2u-internal.atlassian.net/browse/INF-666)
Imported DiscussionContext in Comment.js
=> fix: lint fixes

src/discussions/data/hooks.js, src/discussions/posts/PostsList.jsx
- Removed the Sidebar in case there are no posts.
https://user-images.githubusercontent.com/26253150/207581845-2a976e50-e2ff-4276-9fd0-aca056f3716a.mov
=> fix: removed side bar incase there are no posts

src/discussions/comments/CommentsView.jsx, src/discussions/comments/comment/CommentHeader.jsx
[INF-684](https://2u-internal.atlassian.net/browse/INF-684)
Add response button does not show when no responses are available
**After**
=> fix: add response button does not show when no responses available

src/index.scss
just the code structure change to meet best practices
=> chore: code style fix

src/discussions/comments/comment/Comment.jsx, src/discussions/comments/comment/Reply.jsx
[inf-706](https://2u-internal.atlassian.net/browse/INF-706)
Page width was increasing due to long comment or reply which is fixed.
**Before**
**After**
=> fix: page width does not increase due to long text

src/discussions/tours/data/redux.test.js, src/discussions/tours/data/slices.js
State of tours was not updated due to current state was not used correctly this PR fixes this issue . 
https://2u-internal.atlassian.net/browse/INF-687
=> fix: resolve tour state update error

public/index.html, src/components/HTMLLoader.jsx
- output is not rendering properly for mathjax when the code is moved to stage or prod. this a test commit to check issue can be resolved by fetching script form a different source.
=> fix: testing mathjax issue fix with script change

public/index.html, src/components/HTMLLoader.jsx
- output format is changed for testing the fix on stage for mathjax rendering.
=> fix: output format changed for mathjax script

public/index.html, src/components/HTMLLoader.jsx, src/discussions/comments/CommentsView.test.jsx
- upgraded mathjax from v2 to v3 for checking if that works in prod. its a test run not sure hence does not guarantee resolution of mathjax rendering.
- commented test cases for now as they are breaking due to script load issues. will fix it if version 3 starts rendering on prod.
=> feat: added mathjax v3 support in platform

public/index.html, src/components/HTMLLoader.jsx, src/discussions/comments/CommentsView.test.jsx
Reverts openedx/frontend-app-discussions#420
Reverting this PR as it broke the UI
=> Revert "feat: added mathjax v3 support in platform"

public/index.html, src/components/HTMLLoader.jsx, src/components/PostPreviewPane.jsx, src/discussions/comments/CommentsView.test.jsx, src/discussions/posts/post/Post.jsx
Final Solution PR: https://2u-internal.atlassian.net/browse/INF-735
- [feat: added mathjax v3 support in platform]
- [fix: overwriting of comments and responses fixed]
- [test cases] fix in progress, these are fixed but depend on the UI changes that need to merge in #407 so won't make part of this PR.
=> Mathjax v3 fix

src/discussions/posts/PostsList.jsx
On my posts page search was using `fetchUserPosts` API which does not allow search by text so changed code to use `fetchThreads` API so it would filter by search text and author . 
https://2u-internal.atlassian.net/browse/INF-734
=> fix: use threads api in case of search

src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js, src/discussions/in-context-topics/data/__factories__/index.js, src/discussions/in-context-topics/data/api.js, src/discussions/in-context-topics/data/api.test.js, src/discussions/in-context-topics/data/redux.test.js, src/discussions/in-context-topics/data/selector.test.jsx, src/discussions/in-context-topics/data/slices.js, src/discussions/in-context-topics/data/thunks.js
Added test cases for redux store manipulation, API responses, and selectors
https://2u-internal.atlassian.net/browse/INF-725
I tested my changes by running the command "npm run test [relative path of the file]
=>  test: added redux, api and selector test cases for in context topics

src/data/constants.js, src/discussions/in-context-topics/TopicPostsView.jsx, src/discussions/in-context-topics/components/BackButton.jsx, src/discussions/in-context-topics/data/slices.js, src/discussions/posts/PostsList.jsx
[INF-768](https://2u-internal.atlassian.net/browse/INF-768)
This PR resolved the following issues 
1. If the page is refreshed when viewing unit names in the Discussion > Topics tab, the subsection name changes to an unnamed subsection and the list just keeps loading.
2. If the page is refreshed when a viewing post is in Discussion > Topics tab, the unit (topic) name changes to an unnamed topic.
1. I added a topics v3 API call on the Topic/Unit post page because the page hard refreshed v3 topics data was not available in the store. 
2. Add a mini loader on the selected topic/unit name while API is in progress to prevent to display of unnamed during in-progress.
1. Go to the discussion MFE tab 
2. Select the topics tab
3. Select any course-wide topic or any subsection
4. You will see the …
=> fix: unnamed topic/unit issue in inContext topics

public/index.html
**[INF-754](https://2u-internal.atlassian.net/browse/INF-754)**
This PR is Implementing getFeedback widget to get user feedback in a central place. The added script will show the widget on the screen bottom and the user will available to submit feedback. This PR is temporary and its purpose is to test the response time from getFeedback servers on stage env.
1. Go to discussions MFE
2. You will see a widget on `share feedback` and click on it
3. Enter feedback and submit it. 
* [❌ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ❌] Is there adequate test coverage for your changes?
=> temp: testing getFeedback widget response time

src/components/HTMLLoader.jsx, src/components/PostPreviewPane.jsx
Post was loading slow after click. Preview delay was affecting post loading time. [INF-769](https://2u-internal.atlassian.net/browse/INF-769)
Tested by changing delay time in all scenarios.
=> fix: post loading slow

src/discussions/post-comments/PostCommentsView.jsx
[INF-799](https://2u-internal.atlassian.net/browse/INF-799) 
2px border is added to focused post
**Before** 
[49f4ffb3-7c7f-40bd-aae9-a44f6248c22a.webm](https://user-images.githubusercontent.com/73840786/222527583-9618ce54-b052-472d-be22-53a32dda98b7.webm)
**After**
[7567b455-0fe6-46d0-988b-4f9fac624fb6.webm](https://user-images.githubusercontent.com/73840786/222527569-2b7da65a-8e98-4358-92d7-63b571ebcbfe.webm)
=> style: add border on focused post

src/discussions/posts/PostsList.jsx
Fix the issue when the search on the "My Posts" tab doesn't work
This is a backport from the master branch: https://github.com/openedx/frontend-app-discussions/pull/419
=> fix: my posts tab search

src/discussions/learners/LearnerPostsView.jsx, src/discussions/learners/LearnerPostsView.test.jsx, src/discussions/learners/LearnersView.jsx, src/discussions/learners/LearnersView.test.jsx, src/discussions/learners/data/__factories__/learners.factory.js, src/discussions/learners/data/redux.test.jsx, src/discussions/learners/data/selector.test.jsx, src/discussions/learners/data/selectors.js, src/discussions/learners/test-utils.js
[INF-811](https://2u-internal.atlassian.net/browse/INF-811)
Add test cases for the following cases.
1. Selector
a. Need to remove selectLearnerLastLogin and selectLearner selectors because these selectors are not using in any 
component.
2. Factory
a. It should display learners based on condition activeFlags <= len 
3. LearnerCard
a. It should create a post with the logged in user name to meet this condition (learner.username === learnerUsername)
4. LearnerFilterBar
a. It should filter the learner’s list based on sort-reported filter
5. LearnerFooter
a. It should display reported message by passing activeFlags or inactiveFlags in the factory of leaner.
b. It should display previouslyReported message by passing activeFlags or inactiveFlags in the factory of leaner.
6. LearnerPostFilterbar …
=> test: added test cases of learners and post

src/discussions/common/AuthorLabel.jsx, src/discussions/common/AuthorLabel.test.jsx, src/discussions/common/HoverCard.jsx, src/discussions/post-comments/PostCommentsView.test.jsx, src/discussions/posts/post/Post.jsx, src/discussions/posts/post/PostFooter.jsx, src/discussions/posts/post/PostFooter.test.jsx
[INF-804](https://2u-internal.atlassian.net/browse/INF-804)
- Fixed slightly larger vertical height of the post which was due to PostFooter unnecessaary rendering.
- Removed hoverstate from Author Label.
- In endorsement badge adjusted both Author icon and label within tool tip and removed hoverstate from time stamp.
- Adds tooltip in hoverCard for endorsement badge.
**Screen Recording:**
**ScreenShots:**
=> fix: fix post height and remove overstate from author label

public/index.html, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/discussions-home/FeedbackWrapper.jsx
https://2u-internal.atlassian.net/browse/INF-816
Added support for different forms for Learners and CourseAdmin, CourseStaff, UserIsGroupTa, UserIsStaff 
This PR is tested locally on `devstack` with both learner and staff account.
Please describe in detail how you tested your changes.
=> feat: added support for dual feedback forms

src/components/NavigationBar/data/__factories__/index.js, src/components/NavigationBar/data/__factories__/navigationBar.factory.js, src/components/NavigationBar/data/api.js, src/components/NavigationBar/data/api.test.js, src/components/NavigationBar/data/thunks.js, src/discussions/discussions-home/DiscussionsHome.test.jsx
[INF-343](https://2u-internal.atlassian.net/browse/INF-343)
Added Following cases:
1. Add Navigation Bar Factory
2. API Test Cases
a. It successfully get navigation tabs
b. It failed to get navigation tabs
c. It denied to get navigation tabs
d. It denied to get navigation bar when user has no access on course
3. CourseTabsNavigation
a. It should display navigation tabs
npm run test
=> test: added test cases of navigation bar (#487)

src/components/HTMLLoader.jsx
[INF-840](https://2u-internal.atlassian.net/browse/INF-840)
Currently, Discussions MFE has many frequent JS errors on the new relic dashboard.
This PR intends to resolve `Typeset failed: Cannot read properties of undefined (reading 'defaultPageReady')`
=> fix: typeset failed: Cannot read properties of undefined

src/index.jsx
This PR this enabling the Profiler on production build to collect the performance measurements. This PR will revert after collecting the stats.
=> chore: enable profiler on production build

src/discussions/posts/post/LikeButton.jsx, src/discussions/utils.js, src/index.jsx, src/index.scss
This PR fixes several issues like the endorse and answer icon nd button option. like button click issues. style-related height and width issues and remove the Profiler configuration.
=> fix: after optimization issues

src/components/Spinner.jsx, src/discussions/common/HoverCard.test.jsx, src/discussions/post-comments/PostCommentsView.test.jsx, src/discussions/post-comments/data/api.js
MFE optimization had done a lot of component updates and restructuring. So many tests are failing now. This PR aims to resolve these components failed test cases.
HoverCard - Done
PostCommentsView - In progress
=> test: fixed test cases after MFE optimization

src/discussions/common/ActionsDropdown.jsx, src/discussions/common/ActionsDropdown.test.jsx, src/discussions/common/HoverCard.jsx, src/discussions/common/HoverCard.test.jsx, src/discussions/data/hooks.js, src/discussions/data/hooks.test.jsx, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/discussions-home/DiscussionsRestrictionBanner.jsx, src/discussions/discussions-home/DiscussionsRestrictionBanner.test.jsx, src/discussions/in-context-topics/TopicPostsView.test.jsx, src/discussions/messages.js, src/discussions/post-comments/PostCommentsView.test.jsx, src/discussions/post-comments/comments/CommentsView.jsx, src/discussions/post-comments/comments/comment/Comment.jsx, src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/utils.js
[INF-828](https://2u-internal.atlassian.net/browse/INF-828)
Integrated already build UI with the API change in [INF-826](https://2u-internal.atlassian.net/browse/INF-826)
=> feat: integrated backend discussions restriction with MFE

src/discussions/common/HoverCard.test.jsx, src/discussions/post-comments/PostCommentsView.test.jsx, src/discussions/post-comments/data/__factories__/comments.factory.js
[INF-926](https://2u-internal.atlassian.net/browse/INF-926)
Some test cases were failing due to structure of comments factory used in PostCommentsView Tests.
This ticket intends to add those removed test cases and fix comments factory.
=> test: fixed postcommentsview test cases

renovate.json
[INF-937](https://2u-internal.atlassian.net/browse/INF-937)
Added required fields in Renovate.json based on shared template [here](https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html#javascript-dependency-update-automation-is-enabled)
=> chore: added renovate file structure based on provided template

package-lock.json, package.json
-  Update react-redux
Please describe in detail how you tested your changes.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
|      |      |
=> build: update react-redux

src/components/NavigationBar/CourseTabsNavigation.jsx, src/index.scss
- Remove the fixed height of the learning header
=> fix: learning header constant height

src/discussions/common/AuthorLabel.jsx, src/discussions/post-comments/comments/CommentsView.jsx, src/index.scss
- Fixed font family on page 
- Fixed borders on action bar on mobile view
- Fixed newest first text overlap another text
- Fixed displaying user name on mobile view
=> feat: Enhancements to page (quince.master)

src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/posts/post-actions-bar/PostActionsBar.jsx, src/discussions/posts/post-actions-bar/actionBar.scss, src/index.scss
[INF-1184](https://2u-internal.atlassian.net/browse/INF-1184)
fixed UI issues of discussion for incontext sidebar based on Figma [Legacy Notifications vs Discussions Sidebar](https://www.figma.com/proto/PwKdrc6pQhlw5XJaB7hBrb/Legacy-Notifications-vs-Discussions-Sidebar?page-id=0%3A1&type=design&node-id=28-14107&viewport=625%2C3258%2C0.21&t=Cq10PY4QgOnlrpuh-9&scaling=scale-down&starting-point-node-id=28%3A14107&hotspot-hints=0&show-proto-sidebar=1).
=> fix: fixed UI issues of discussion for incontext sidebar

src/components/NavigationBar/CourseTabsNavigation.jsx, src/discussions/common/AuthorLabel.jsx, src/discussions/common/HoverCard.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/post-comments/PostCommentsView.jsx, src/discussions/post-comments/comments/CommentsView.jsx, src/discussions/post-comments/comments/comment/Comment.jsx, src/index.scss
[INF-1220](https://2u-internal.atlassian.net/browse/INF-1220)
1. Updated the direct color codes in scss file with paragon color variables in discussion MFE.
2. Fixed hover color issue throughout discussion MFE
3. Fixed ZIndex issue of card
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
=> fix: fixed hover color issue throughout MFE

src/discussions/posts/post/PostHeader.jsx
Description
Fixed the question icon on read posts and updated the background color to match.
Also fixed the question icon position in the detailed post view.
Before:
After:
=> fix: fixed question icon and its position

src/components/NavigationBar/data/slice.js, src/discussions/data/selectors.js, src/discussions/discussions-home/DiscussionsHome.jsx
[INF-1100](https://2u-internal.atlassian.net/browse/INF-1100)
I've limited the display of the content unavailable UI exclusively to learners who haven't enrolled in the course.
**Screenshot**
=> fix: now content unavailable ui is only for learner

src/components/NavigationBar/CourseTabsNavigation.jsx, src/components/NavigationBar/data/api.js, src/components/NavigationBar/data/thunks.js, src/discussions/content-unavailable/ContentUnavailable.jsx, src/discussions/data/hooks.js, src/discussions/data/selectors.js, src/discussions/discussions-home/DiscussionsHome.jsx
- `isEnrolled` data was not available in the inContext sidebar view. `isEnrolled` is available in course_meta_data api which was not calling from inContext.
=> fix: user content unavailable content issue for learner

src/discussions/common/AuthorLabel.jsx, src/discussions/discussions-home/DiscussionSidebar.jsx, src/discussions/post-comments/comments/comment/Reply.jsx, src/index.scss
**Fix user icon shrinkage**
Before
After
**Fix username overlapping with comment text, in cases when username is too long**
Before
After
**Added more space for long username by moving additional post data to the next row**
Before
After
**Fix sidebar width on tablet resolutions**
On tablet resolutions, the sidebar becomes larger than on desktop. We believe this is illogical and fixed it
https://github.com/openedx/frontend-app-discussions/assets/19806032/3cacab34-76fa-454a-8911-43f68438860c
Before
After
=> fix: Discussions UI fixes on mobile resolutions

src/discussions/content-unavailable/ContentUnavailable.jsx, src/discussions/data/hooks.js, src/discussions/discussions-home/DiscussionSidebar.jsx, src/discussions/discussions-home/DiscussionsHome.jsx, src/discussions/empty-posts/EmptyLearners.jsx, src/discussions/empty-posts/EmptyPosts.jsx, src/discussions/empty-posts/EmptyTopics.jsx, src/discussions/in-context-topics/components/EmptyTopics.jsx, src/discussions/post-comments/PostCommentsView.jsx, src/index.scss
Discussions had imbalance between the content column and the sidebar for smaller view. The content column width is insufficient to display comments and responses effectively. 
**Before:**
**Desktop View:**
**Tablet View:**
=> fix: fixed limited content visibility due to oversized sidebar

src/components/HTMLLoader.jsx
[INF-1324](https://2u-internal.atlassian.net/browse/INF-1324)
Clicking a link in the context sidebar post now redirects the user to a new tab instead of opening the link within the iframe.
=> fix: fix redirection to new tab issue

src/discussions/common/ActionsDropdown.jsx, src/discussions/common/AuthorLabel.jsx, src/index.scss
[INF-1395](https://2u-internal.atlassian.net/browse/INF-1395)
follow up of [INF-1363](https://2u-internal.atlassian.net/browse/INF-1363) [PR](https://github.com/openedx/frontend-app-discussions/pull/697)
**Actions Dropdown**
=> fix: fixed font-size of load more buttons and add a post heading

src/discussions/data/api.js
Reverts openedx/frontend-app-discussions#702
=> Revert "feat: updated config api URL version"

.github/workflows/ci.yml
This reverts commit 472bbe2d96e98c0b7a32121db42ee9c9b498683a (#740).
=> revert: revert: "test: Remove support for Node 18 (#736)"

package-lock.json, src/discussions/posts/data/hooks.js
=> Sync master to design tokens

package-lock.json, package.json, src/discussions/data/selectors.js, src/discussions/data/slices.js, src/discussions/post-comments/PostCommentsView.test.jsx, src/discussions/post-comments/comments/comment/CommentEditor.jsx, src/discussions/post-comments/data/api.js, src/discussions/post-comments/data/api.test.js, src/discussions/post-comments/data/thunks.js, src/discussions/post-comments/messages.js, src/discussions/posts/data/api.js, src/discussions/posts/data/thunks.js, src/discussions/posts/post-editor/PostEditor.jsx, src/discussions/posts/post-editor/PostEditor.test.jsx, src/discussions/posts/post-editor/messages.js, src/discussions/posts/post-editor/mocksData/react-google-recaptcha.jsx
Include a description of your changes here, along with a link to any relevant Jira tickets and/or GitHub issues.
Please describe in detail how you tested your changes.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
|      |      |
=> feat: added captcha to discussion post creation
